package restproviders

import "github.com/memohai/connect-it/packages/core/connector"

// providerIconURLs covers providers whose icon is unavailable from the current
// Simple Icons catalog. Prefer an official brand asset; use a maintained icon
// library only when the provider does not expose a stable public asset.
var providerIconURLs = map[connector.Type]string{
	"activecampaign": "https://www.activecampaign.com/dist/favicon-180x180.png",
	"ahrefs":         "https://static.ahrefs.com/favicon.svg?v=2",
	"apify":          "https://api.iconify.design/devicon:apify.svg",
	"apollo":         "https://www.apollo.io/icon.svg?icon.11df6mby0rn6l.svg",
	"beehiiv":        "https://beehiiv-marketing-images.s3.amazonaws.com/Redesign2023/favicon.png",
	"buildium":       "https://www.buildium.com/wp-content/uploads/2017/06/Buildium-favicon.png",
	"chargebee":      "https://www.chargebee.com/static/resources/brand/apple-touch-icon.png?v=1",
	"cin7_core":      "https://www.cin7.com/hubfs/image/logo/cin7/cin7-favicon-2023.jpeg",
	"close":          "https://cdn.prod.website-files.com/61717799a852418a278cfa9b/66268a52e0119bfb4fb75e16_webclip.png",
	"cohere":         "https://cohere.com/apple-touch-icon.png",
	"customer_io":    "https://customer.io/favicon.svg",
	"cyberimpact":    "https://www.cyberimpact.com/wp-content/uploads/2020/02/cropped-cyberimpact-180x180.png",
	"dub":            "https://assets.dub.co/favicons/apple-touch-icon.png",
	"easypost":       "https://www.easypost.com/wp-content/uploads/2025/03/icon.svg",
	"exa":            "https://exa.ai/images/favicon-32x32.png",
	"folk":           "https://cdn.prod.website-files.com/626be00c396339c5a816353b/6a16a47cc6dbf48bc20b20d7_logo.png",
	"freshdesk":      "https://www.freshworks.com/favicons/apple-touch-icon.png",
	"freshsales":     "https://www.freshworks.com/favicons/apple-touch-icon.png",
	"gorgias":        "https://cdn.prod.website-files.com/5e4ff204e7b6f80e402d407a/655f0a311c75248c5ff9756b_Social%20Avatar.png",
	"holded":         "https://www.holded.com/assets/favicons/apple-touch-icon.png",
	"instantly":      "https://cdn.prod.website-files.com/63860c8c65e7bef4a1eeebeb/63f62e4d1df86f1bf7f133d5_cleaned_rounded.png",
	"jotform":        "https://cdn.jotfor.ms/assets/img/favicons/favicon-2021.svg",
	"klaviyo":        "https://www.klaviyo.com/icons/icon-512x512.png",
	"kustomer":       "https://api.iconify.design/logos:kustomer.svg",
	"leadfeeder":     "https://www.leadfeeder.com/favicon.svg",
	"leadmagic":      "https://leadmagic.io/favicon.svg?v=20260520",
	"lemlist":        "https://www.lemlist.com/favicon.ico",
	"lob":            "https://cdn.prod.website-files.com/5e1e5c62fa3d4447af417098/6348790a6940a6b92f0a188f_Lob%20Webclip.png",
	"mailjet":        "https://www.mailjet.com/wp-content/themes/simpletexting-theme-blank/assets/favicon/apple-touch-icon-512x512.png",
	"omnisend":       "https://www.omnisend.com/wp-content/uploads/2022/07/cropped-favi-180x180.png",
	"openai":         "https://api.iconify.design/selfhst:openai.svg",
	"pinecone":       "https://api.iconify.design/logos:pinecone-icon.svg",
	"pipedrive":      "https://api.iconify.design/logos:pipedrive.svg",
	"recruitcrm":     "https://recruitcrm.io/favicon.ico",
	"reply_io":       "https://reply.io/favicon.ico",
	"sendgrid":       "https://api.iconify.design/logos:sendgrid-icon.svg",
	"ship_bob":       "https://www.shipbob.com/wp-content/themes/shipbob-2022/resources/icons/touch.png",
	"ship_station":   "https://www.shipstation.com/wp-content/uploads/2026/02/Station-Favicon-2026.svg",
	"shippo":         "https://cdn.prod.website-files.com/6462967bbf70fa5b5b227351/662680002605ee5735982802_img-shipp-favicon-256x256.png",
	"smartlead":      "https://cdn.prod.website-files.com/6204a703ff61516512c04f55/6a4b63964faaeefe3b922773_smartleat-campaign-fav.png",
	"stay_ai":        "https://stay.ai/wp-content/uploads/2025/02/cropped-favicon-180x180.png",
	"store_leads":    "https://storeleads.app/img/favicon.png",
	"theirstack":     "https://theirstack.com/static/generated/apple-touch-icon.png",
	"together_ai":    "https://cdn.prod.website-files.com/69654e88dce9154b5f1206dd/69a59cff65ed0f267dd2fbe8_touchicon.png",
	"twilio":         "https://api.iconify.design/logos:twilio-icon.svg",
	"typefully":      "https://typefully.com/icon/apple-icon.png",
	"weaviate":       "https://api.iconify.design/selfhst:weaviate.svg",
	"wiza":           "https://cdn.prod.website-files.com/6883340bfc8ef2bdd680f851/688a2988a4fad24aeff16d79_webclip.png",
}
