// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AdminDeleteConnectionData, AdminDeleteConnectionErrors, AdminDeleteConnectionResponses, AdminListConnectorsData, AdminListConnectorsErrors, AdminListConnectorsResponses, AdminReauthConnectionData, AdminReauthConnectionErrors, AdminReauthConnectionResponses, BeginOAuthConnectionData, BeginOAuthConnectionErrors, BeginOAuthConnectionResponses, ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateApiKeyConnectionData, CreateApiKeyConnectionErrors, CreateApiKeyConnectionResponses, CreateApiTokenData, CreateApiTokenResponses, CreateMcpSessionData, CreateMcpSessionErrors, CreateMcpSessionResponses, DeleteApiTokenData, DeleteApiTokenErrors, DeleteApiTokenResponses, DeleteConfigData, DeleteConfigErrors, DeleteConfigResponses, DeleteConnectionData, DeleteConnectionErrors, DeleteConnectionResponses, GetConfigData, GetConfigErrors, GetConfigResponses, GetConfigSchemaData, GetConfigSchemaErrors, GetConfigSchemaResponses, GetConnectionData, GetConnectionErrors, GetConnectionResponses, GetConnectorData, GetConnectorErrors, GetConnectorResponses, HealthzData, HealthzResponses, ListApiTokensData, ListApiTokensResponses, ListAuthMethodsData, ListAuthMethodsErrors, ListAuthMethodsResponses, ListConnectionsData, ListConnectionsResponses, ListConnectorsData, ListConnectorsErrors, ListConnectorsResponses, LoginData, LoginErrors, LoginResponses, OauthCallbackData, PutConfigData, PutConfigErrors, PutConfigResponses, ReauthConnectionData, ReauthConnectionErrors, ReauthConnectionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 修改管理员密码
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => {
    return (options.client ?? client).put<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
        url: '/admin/account/password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 列出 API token（不含明文）
 */
export const listApiTokens = <ThrowOnError extends boolean = false>(options?: Options<ListApiTokensData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListApiTokensResponses, unknown, ThrowOnError>({
        url: '/admin/api-tokens',
        ...options
    });
};

/**
 * 创建 API token（明文仅在响应中出现一次）
 */
export const createApiToken = <ThrowOnError extends boolean = false>(options: Options<CreateApiTokenData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateApiTokenResponses, unknown, ThrowOnError>({
        url: '/admin/api-tokens',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 撤销 API token
 */
export const deleteApiToken = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTokenData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiTokenResponses, DeleteApiTokenErrors, ThrowOnError>({
        url: '/admin/api-tokens/{id}',
        ...options
    });
};

/**
 * 列出全部连接（运维视角，不含 credential）
 */
export const listConnections = <ThrowOnError extends boolean = false>(options?: Options<ListConnectionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListConnectionsResponses, unknown, ThrowOnError>({
        url: '/admin/connections',
        ...options
    });
};

/**
 * 删除连接（运维）
 */
export const adminDeleteConnection = <ThrowOnError extends boolean = false>(options: Options<AdminDeleteConnectionData, ThrowOnError>) => {
    return (options.client ?? client).delete<AdminDeleteConnectionResponses, AdminDeleteConnectionErrors, ThrowOnError>({
        url: '/admin/connections/{id}',
        ...options
    });
};

/**
 * 生成重授权链接（运维转交给对应用户打开）
 */
export const adminReauthConnection = <ThrowOnError extends boolean = false>(options: Options<AdminReauthConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<AdminReauthConnectionResponses, AdminReauthConnectionErrors, ThrowOnError>({
        url: '/admin/connections/{id}/reauth',
        ...options
    });
};

/**
 * 列出全部 Connector（管理界面，cookie 鉴权）
 */
export const adminListConnectors = <ThrowOnError extends boolean = false>(options?: Options<AdminListConnectorsData, ThrowOnError>) => {
    return (options?.client ?? client).get<AdminListConnectorsResponses, AdminListConnectorsErrors, ThrowOnError>({
        url: '/admin/connectors',
        ...options
    });
};

/**
 * Connector 的认证方式与凭证字段（供创建 connection 的表单）
 */
export const listAuthMethods = <ThrowOnError extends boolean = false>(options: Options<ListAuthMethodsData, ThrowOnError>) => {
    return (options.client ?? client).get<ListAuthMethodsResponses, ListAuthMethodsErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/auth-methods',
        ...options
    });
};

/**
 * 删除 Connector 配置
 */
export const deleteConfig = <ThrowOnError extends boolean = false>(options: Options<DeleteConfigData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteConfigResponses, DeleteConfigErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config',
        ...options
    });
};

/**
 * 读取 Connector 配置（Secret 只回显已设置的 key）
 */
export const getConfig = <ThrowOnError extends boolean = false>(options: Options<GetConfigData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConfigResponses, GetConfigErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config',
        ...options
    });
};

/**
 * 写入 Connector 配置（public 全量替换、secrets 增量合并，空串删除）
 */
export const putConfig = <ThrowOnError extends boolean = false>(options: Options<PutConfigData, ThrowOnError>) => {
    return (options.client ?? client).put<PutConfigResponses, PutConfigErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Connector 配置表单元数据（由 Definition 的 ConfigFields 生成）
 */
export const getConfigSchema = <ThrowOnError extends boolean = false>(options: Options<GetConfigSchemaData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConfigSchemaResponses, GetConfigSchemaErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config-schema',
        ...options
    });
};

/**
 * 管理员登录，成功后下发会话 cookie
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: '/admin/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 健康检查
 */
export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({
        url: '/healthz',
        ...options
    });
};

/**
 * 用 API key / 自定义凭证创建连接，返回其持久 ID
 */
export const createApiKeyConnection = <ThrowOnError extends boolean = false>(options: Options<CreateApiKeyConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateApiKeyConnectionResponses, CreateApiKeyConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/api-key',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 发起 OAuth 授权：立即创建 pending 连接并返回其持久 ID 与授权 URL
 */
export const beginOAuthConnection = <ThrowOnError extends boolean = false>(options: Options<BeginOAuthConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<BeginOAuthConnectionResponses, BeginOAuthConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/oauth',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 删除连接
 */
export const deleteConnection = <ThrowOnError extends boolean = false>(options: Options<DeleteConnectionData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/{id}',
        ...options
    });
};

/**
 * 查询连接状态（pending / active / authorization_failed / reauth_required）
 */
export const getConnection = <ThrowOnError extends boolean = false>(options: Options<GetConnectionData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConnectionResponses, GetConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/{id}',
        ...options
    });
};

/**
 * 对既有连接重新发起授权（ID 不变）
 */
export const reauthConnection = <ThrowOnError extends boolean = false>(options: Options<ReauthConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<ReauthConnectionResponses, ReauthConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/{id}/reauth',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 列出全部 Connector（含运行状态）
 */
export const listConnectors = <ThrowOnError extends boolean = false>(options?: Options<ListConnectorsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListConnectorsResponses, ListConnectorsErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connectors',
        ...options
    });
};

/**
 * 查询单个 Connector
 */
export const getConnector = <ThrowOnError extends boolean = false>(options: Options<GetConnectorData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConnectorResponses, GetConnectorErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connectors/{type}',
        ...options
    });
};

/**
 * 签发绑定单个 Connection 的短期 MCP session token
 */
export const createMcpSession = <ThrowOnError extends boolean = false>(options: Options<CreateMcpSessionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMcpSessionResponses, CreateMcpSessionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/mcp-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * OAuth 回调（provider 跳转回来，无鉴权，靠一次性 state）
 */
export const oauthCallback = <ThrowOnError extends boolean = false>(options?: Options<OauthCallbackData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        url: '/v1/oauth/callback',
        ...options
    });
};
