// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AdminDeleteConnectionData, AdminDeleteConnectionErrors, AdminDeleteConnectionResponses, AdminListConnectorsData, AdminListConnectorsErrors, AdminListConnectorsResponses, AdminReauthConnectionData, AdminReauthConnectionErrors, AdminReauthConnectionResponses, BeginOAuthConnectionData, BeginOAuthConnectionErrors, BeginOAuthConnectionResponses, ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateApiKeyConnectionData, CreateApiKeyConnectionErrors, CreateApiKeyConnectionResponses, CreateApiTokenData, CreateApiTokenResponses, CreateMcpSessionData, CreateMcpSessionErrors, CreateMcpSessionResponses, DeleteApiTokenData, DeleteApiTokenErrors, DeleteApiTokenResponses, DeleteConfigData, DeleteConfigErrors, DeleteConfigResponses, DeleteConnectionData, DeleteConnectionErrors, DeleteConnectionResponses, GetConfigData, GetConfigErrors, GetConfigResponses, GetConfigSchemaData, GetConfigSchemaErrors, GetConfigSchemaResponses, GetConnectionData, GetConnectionErrors, GetConnectionResponses, GetConnectorData, GetConnectorErrors, GetConnectorResponses, GetVersionData, GetVersionResponses, HealthzData, HealthzResponses, ListApiTokensData, ListApiTokensResponses, ListAuthMethodsData, ListAuthMethodsErrors, ListAuthMethodsResponses, ListConnectionsData, ListConnectionsResponses, ListConnectorsData, ListConnectorsErrors, ListConnectorsResponses, LoginData, LoginErrors, LoginResponses, OauthCallbackData, OauthCallbackResponses, PutConfigData, PutConfigErrors, PutConfigResponses, ReauthConnectionData, ReauthConnectionErrors, ReauthConnectionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Change the administrator password
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => {
    return (options.client ?? client).put<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
        url: '/admin/account/password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List API tokens without plaintext
 */
export const listApiTokens = <ThrowOnError extends boolean = false>(options?: Options<ListApiTokensData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListApiTokensResponses, unknown, ThrowOnError>({
        url: '/admin/api-tokens',
        ...options
    });
};

/**
 * Create an API token; the plaintext appears in this response only
 */
export const createApiToken = <ThrowOnError extends boolean = false>(options: Options<CreateApiTokenData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateApiTokenResponses, unknown, ThrowOnError>({
        url: '/admin/api-tokens',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Revoke an API token
 */
export const deleteApiToken = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTokenData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiTokenResponses, DeleteApiTokenErrors, ThrowOnError>({
        url: '/admin/api-tokens/{id}',
        ...options
    });
};

/**
 * List every connection for operators, without credentials
 */
export const listConnections = <ThrowOnError extends boolean = false>(options?: Options<ListConnectionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListConnectionsResponses, unknown, ThrowOnError>({
        url: '/admin/connections',
        ...options
    });
};

/**
 * Delete a connection, operator view
 */
export const adminDeleteConnection = <ThrowOnError extends boolean = false>(options: Options<AdminDeleteConnectionData, ThrowOnError>) => {
    return (options.client ?? client).delete<AdminDeleteConnectionResponses, AdminDeleteConnectionErrors, ThrowOnError>({
        url: '/admin/connections/{id}',
        ...options
    });
};

/**
 * Mint a re-authorization link for an operator to hand to the right end user
 */
export const adminReauthConnection = <ThrowOnError extends boolean = false>(options: Options<AdminReauthConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<AdminReauthConnectionResponses, AdminReauthConnectionErrors, ThrowOnError>({
        url: '/admin/connections/{id}/reauth',
        ...options
    });
};

/**
 * List every connector for the admin UI, cookie authenticated
 */
export const adminListConnectors = <ThrowOnError extends boolean = false>(options?: Options<AdminListConnectorsData, ThrowOnError>) => {
    return (options?.client ?? client).get<AdminListConnectorsResponses, AdminListConnectorsErrors, ThrowOnError>({
        url: '/admin/connectors',
        ...options
    });
};

/**
 * Auth methods and credential fields of a connector, for the create-connection form
 */
export const listAuthMethods = <ThrowOnError extends boolean = false>(options: Options<ListAuthMethodsData, ThrowOnError>) => {
    return (options.client ?? client).get<ListAuthMethodsResponses, ListAuthMethodsErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/auth-methods',
        ...options
    });
};

/**
 * Delete connector config
 */
export const deleteConfig = <ThrowOnError extends boolean = false>(options: Options<DeleteConfigData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteConfigResponses, DeleteConfigErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config',
        ...options
    });
};

/**
 * Read connector config; secrets echo back only the keys that are set
 */
export const getConfig = <ThrowOnError extends boolean = false>(options: Options<GetConfigData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConfigResponses, GetConfigErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config',
        ...options
    });
};

/**
 * Write connector config; public is replaced wholesale, secrets are merged and an empty string deletes
 */
export const putConfig = <ThrowOnError extends boolean = false>(options: Options<PutConfigData, ThrowOnError>) => {
    return (options.client ?? client).put<PutConfigResponses, PutConfigErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Config form metadata for a connector, derived from the ConfigFields of its Definition
 */
export const getConfigSchema = <ThrowOnError extends boolean = false>(options: Options<GetConfigSchemaData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConfigSchemaResponses, GetConfigSchemaErrors, ThrowOnError>({
        url: '/admin/connectors/{type}/config-schema',
        ...options
    });
};

/**
 * Log in as administrator and receive a session cookie
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: '/admin/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health check
 */
export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({
        url: '/healthz',
        ...options
    });
};

/**
 * Create a connection from an API key or custom credential and return its durable ID
 */
export const createApiKeyConnection = <ThrowOnError extends boolean = false>(options: Options<CreateApiKeyConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateApiKeyConnectionResponses, CreateApiKeyConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/api-key',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Start an OAuth authorization: create a pending connection and return its durable ID and authorization URL
 */
export const beginOAuthConnection = <ThrowOnError extends boolean = false>(options: Options<BeginOAuthConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<BeginOAuthConnectionResponses, BeginOAuthConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/oauth',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a connection
 */
export const deleteConnection = <ThrowOnError extends boolean = false>(options: Options<DeleteConnectionData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/{id}',
        ...options
    });
};

/**
 * Get connection status (pending / active / reauth_required and so on)
 */
export const getConnection = <ThrowOnError extends boolean = false>(options: Options<GetConnectionData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConnectionResponses, GetConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/{id}',
        ...options
    });
};

/**
 * Re-authorize an existing connection, keeping the same ID
 */
export const reauthConnection = <ThrowOnError extends boolean = false>(options: Options<ReauthConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<ReauthConnectionResponses, ReauthConnectionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connections/{id}/reauth',
        ...options
    });
};

/**
 * List every connector with its runtime status
 */
export const listConnectors = <ThrowOnError extends boolean = false>(options?: Options<ListConnectorsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListConnectorsResponses, ListConnectorsErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connectors',
        ...options
    });
};

/**
 * Get a single connector
 */
export const getConnector = <ThrowOnError extends boolean = false>(options: Options<GetConnectorData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConnectorResponses, GetConnectorErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/connectors/{type}',
        ...options
    });
};

/**
 * Issue a short-lived MCP session token aggregating several connections
 */
export const createMcpSession = <ThrowOnError extends boolean = false>(options: Options<CreateMcpSessionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMcpSessionResponses, CreateMcpSessionErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/v1/mcp-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * OAuth callback where the provider redirects back; unauthenticated and secured by a single-use state
 */
export const oauthCallback = <ThrowOnError extends boolean = false>(options?: Options<OauthCallbackData, ThrowOnError>) => {
    return (options?.client ?? client).get<OauthCallbackResponses, unknown, ThrowOnError>({
        url: '/v1/oauth/callback',
        ...options
    });
};

/**
 * Get the running service version
 */
export const getVersion = <ThrowOnError extends boolean = false>(options?: Options<GetVersionData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVersionResponses, unknown, ThrowOnError>({
        url: '/version',
        ...options
    });
};
