// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiErrorResponse = {
    /**
     * Error 是稳定、机器可读的错误码。
     */
    error?: string;
    /**
     * Message 可安全返回调用方，不含 Provider 原始响应或 credential 值。
     */
    message?: string;
    /**
     * RetryAfterSeconds 仅在已知正数重试延迟时出现。
     */
    retry_after_seconds?: number;
    /**
     * Temporary 表示稍后重试是否可能成功。
     */
    temporary?: boolean;
};

export type ApiAdminBeginOAuthRequest = {
    alias?: string;
    auth_method: string;
    connector_type: string;
};

export type ApiAuthMethodDto = {
    credential_fields?: Array<ApiConfigFieldDto>;
    key?: string;
    label?: string;
    type?: string;
};

export type ApiBeginOAuthRequest = {
    alias?: string;
    auth_method: string;
    connector_type: string;
    redirect_url?: string;
};

export type ApiBeginOAuthResponse = {
    authorization_url?: string;
    connection_id?: string;
};

export type ApiChangePasswordRequest = {
    password?: string;
};

export type ApiConfigFieldDto = {
    default_value?: string;
    description?: string;
    input_type?: string;
    key?: string;
    label?: string;
    options?: Array<string>;
    pattern?: string;
    required?: boolean;
    secret?: boolean;
};

export type ApiConfigResponse = {
    connector_type?: string;
    public?: {
        [key: string]: unknown;
    };
    schema_version?: number;
    secret_keys_set?: Array<string>;
    updated_at?: string;
};

export type ApiCreateApiKeyRequest = {
    alias?: string;
    auth_method: string;
    connector_type: string;
    fields: {
        [key: string]: string;
    };
};

export type ApiCreateConnectionResponse = {
    connection_id?: string;
};

export type ApiCreateMcpSessionRequest = {
    /**
     * Connections 将 Session-local alias 映射到持久 Connection UUID。
     */
    connections?: {
        [key: string]: string;
    };
    /**
     * ToolAllowlist 区分三态：省略时固化当前 read Tool，[] 授权零 Tool，null
     * 非法；write/destructive Tool 必须显式列出。
     */
    tool_allowlist?: Array<string>;
    /**
     * TTLSeconds 是 Session 有效期；0 使用默认 3600 秒，上限 86400 秒。
     */
    ttl_seconds?: number;
};

export type ApiCreateMcpSessionResponse = {
    expires_at?: string;
    token?: string;
};

export type ApiCreateTokenRequest = {
    name?: string;
};

export type ApiCreateTokenResponse = {
    id?: string;
    token?: string;
};

export type ApiLoginRequest = {
    password?: string;
    username?: string;
};

export type ApiPutConfigRequest = {
    if_match?: string;
    public?: {
        [key: string]: unknown;
    };
    secrets?: {
        [key: string]: string;
    };
};

export type ApiReauthRequest = {
    redirect_url?: string;
};

export type ApiRecredentialRequest = {
    /**
     * Fields 是完整 API-key/custom-credential 字段组；缺少 required 字段会被
     * 拒绝，本端点不是局部 PATCH。
     */
    fields: {
        [key: string]: string;
    };
};

export type ApiValidateConfigRequest = {
    public?: {
        [key: string]: unknown;
    };
    secrets?: {
        [key: string]: string;
    };
};

export type AuthsvcApiTokenView = {
    created_at?: string;
    id?: string;
    name?: string;
    revoked_at?: string;
};

export type CatalogsvcItem = {
    categories?: Array<string>;
    description?: string;
    homepage_url?: string;
    icon_url?: string;
    name?: string;
    status?: StatusStatus;
    type?: string;
};

export type ConnsvcConnectionView = {
    alias?: string;
    auth_method?: string;
    connector_type?: string;
    created_at?: string;
    id?: string;
    status?: string;
};

export type StatusStatus = 'catalog_only' | 'needs_config' | 'config_incompatible' | 'ready' | 'degraded' | 'deprecated' | 'definition_missing';

export type ChangePasswordData = {
    /**
     * 新密码（至少 8 个字符）
     */
    body: ApiChangePasswordRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/account/password';
};

export type ChangePasswordErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListApiTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api-tokens';
};

export type ListApiTokensResponses = {
    /**
     * OK
     */
    200: Array<AuthsvcApiTokenView>;
};

export type ListApiTokensResponse = ListApiTokensResponses[keyof ListApiTokensResponses];

export type CreateApiTokenData = {
    /**
     * token 名称
     */
    body: ApiCreateTokenRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/api-tokens';
};

export type CreateApiTokenErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type CreateApiTokenError = CreateApiTokenErrors[keyof CreateApiTokenErrors];

export type CreateApiTokenResponses = {
    /**
     * Created
     */
    201: ApiCreateTokenResponse;
};

export type CreateApiTokenResponse = CreateApiTokenResponses[keyof CreateApiTokenResponses];

export type DeleteApiTokenData = {
    body?: never;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * token id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/admin/api-tokens/{id}';
};

export type DeleteApiTokenErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type DeleteApiTokenError = DeleteApiTokenErrors[keyof DeleteApiTokenErrors];

export type DeleteApiTokenResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/connections';
};

export type ListConnectionsResponses = {
    /**
     * OK
     */
    200: Array<ConnsvcConnectionView>;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type AdminCreateApiKeyConnectionData = {
    /**
     * 完整凭证字段组按 auth method 的 CredentialFields 填写；alias 可选
     */
    body: ApiCreateApiKeyRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/connections/api-key';
};

export type AdminCreateApiKeyConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Request Timeout
     */
    408: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorResponse;
    /**
     * Bad Gateway
     */
    502: ApiErrorResponse;
    /**
     * Service Unavailable
     */
    503: ApiErrorResponse;
    /**
     * Gateway Timeout
     */
    504: ApiErrorResponse;
};

export type AdminCreateApiKeyConnectionError = AdminCreateApiKeyConnectionErrors[keyof AdminCreateApiKeyConnectionErrors];

export type AdminCreateApiKeyConnectionResponses = {
    /**
     * Created
     */
    201: ApiCreateConnectionResponse;
};

export type AdminCreateApiKeyConnectionResponse = AdminCreateApiKeyConnectionResponses[keyof AdminCreateApiKeyConnectionResponses];

export type AdminBeginOAuthConnectionData = {
    /**
     * alias 为可选展示标签；管理台授权固定回到 connect-it 完成页
     */
    body: ApiAdminBeginOAuthRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/connections/oauth';
};

export type AdminBeginOAuthConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type AdminBeginOAuthConnectionError = AdminBeginOAuthConnectionErrors[keyof AdminBeginOAuthConnectionErrors];

export type AdminBeginOAuthConnectionResponses = {
    /**
     * Created
     */
    201: ApiBeginOAuthResponse;
};

export type AdminBeginOAuthConnectionResponse = AdminBeginOAuthConnectionResponses[keyof AdminBeginOAuthConnectionResponses];

export type AdminDeleteConnectionData = {
    body?: never;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/admin/connections/{id}';
};

export type AdminDeleteConnectionErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type AdminDeleteConnectionError = AdminDeleteConnectionErrors[keyof AdminDeleteConnectionErrors];

export type AdminDeleteConnectionResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type AdminRecredentialConnectionData = {
    /**
     * 完整 credential 字段组；不是局部 PATCH
     */
    body: ApiRecredentialRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/admin/connections/{id}/credential';
};

export type AdminRecredentialConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Request Timeout
     */
    408: ApiErrorResponse;
    /**
     * Conflict
     */
    409: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorResponse;
    /**
     * Bad Gateway
     */
    502: ApiErrorResponse;
    /**
     * Service Unavailable
     */
    503: ApiErrorResponse;
    /**
     * Gateway Timeout
     */
    504: ApiErrorResponse;
};

export type AdminRecredentialConnectionError = AdminRecredentialConnectionErrors[keyof AdminRecredentialConnectionErrors];

export type AdminRecredentialConnectionResponses = {
    /**
     * OK
     */
    200: ConnsvcConnectionView;
};

export type AdminRecredentialConnectionResponse = AdminRecredentialConnectionResponses[keyof AdminRecredentialConnectionResponses];

export type AdminReauthConnectionData = {
    body?: never;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/admin/connections/{id}/reauth';
};

export type AdminReauthConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Conflict
     */
    409: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type AdminReauthConnectionError = AdminReauthConnectionErrors[keyof AdminReauthConnectionErrors];

export type AdminReauthConnectionResponses = {
    /**
     * OK
     */
    200: ApiBeginOAuthResponse;
};

export type AdminReauthConnectionResponse = AdminReauthConnectionResponses[keyof AdminReauthConnectionResponses];

export type AdminListConnectorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/connectors';
};

export type AdminListConnectorsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
};

export type AdminListConnectorsError = AdminListConnectorsErrors[keyof AdminListConnectorsErrors];

export type AdminListConnectorsResponses = {
    /**
     * OK
     */
    200: Array<CatalogsvcItem>;
};

export type AdminListConnectorsResponse = AdminListConnectorsResponses[keyof AdminListConnectorsResponses];

export type ListAuthMethodsData = {
    body?: never;
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/auth-methods';
};

export type ListAuthMethodsErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type ListAuthMethodsError = ListAuthMethodsErrors[keyof ListAuthMethodsErrors];

export type ListAuthMethodsResponses = {
    /**
     * OK
     */
    200: Array<ApiAuthMethodDto>;
};

export type ListAuthMethodsResponse = ListAuthMethodsResponses[keyof ListAuthMethodsResponses];

export type DeleteConfigData = {
    body?: never;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/config';
};

export type DeleteConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type DeleteConfigError = DeleteConfigErrors[keyof DeleteConfigErrors];

export type DeleteConfigResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetConfigData = {
    body?: never;
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/config';
};

export type GetConfigErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * OK
     */
    200: ApiConfigResponse;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type PutConfigData = {
    /**
     * 配置内容；if_match 传上次读到的 updated_at（RFC3339），首次创建留空
     */
    body: ApiPutConfigRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/config';
};

export type PutConfigErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Conflict
     */
    409: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type PutConfigError = PutConfigErrors[keyof PutConfigErrors];

export type PutConfigResponses = {
    /**
     * OK
     */
    200: ApiConfigResponse;
};

export type PutConfigResponse = PutConfigResponses[keyof PutConfigResponses];

export type GetConfigSchemaData = {
    body?: never;
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/config-schema';
};

export type GetConfigSchemaErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type GetConfigSchemaError = GetConfigSchemaErrors[keyof GetConfigSchemaErrors];

export type GetConfigSchemaResponses = {
    /**
     * OK
     */
    200: Array<ApiConfigFieldDto>;
};

export type GetConfigSchemaResponse = GetConfigSchemaResponses[keyof GetConfigSchemaResponses];

export type ValidateConfigData = {
    /**
     * 待校验配置
     */
    body: ApiValidateConfigRequest;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/config:validate';
};

export type ValidateConfigErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type ValidateConfigError = ValidateConfigErrors[keyof ValidateConfigErrors];

export type ValidateConfigResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type VerifyMcpData = {
    body?: never;
    headers: {
        /**
         * 管理台同源写请求固定值 1
         */
        'X-Connect-It-CSRF': string;
    };
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/admin/connectors/{type}/mcp:verify';
};

export type VerifyMcpErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type VerifyMcpError = VerifyMcpErrors[keyof VerifyMcpErrors];

export type VerifyMcpResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type LoginData = {
    /**
     * 用户名与密码
     */
    body: ApiLoginRequest;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type LoginErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type CreateApiKeyConnectionData = {
    /**
     * 凭证字段按 auth method 的 CredentialFields 填写；alias 可选
     */
    body: ApiCreateApiKeyRequest;
    path?: never;
    query?: never;
    url: '/v1/connections/api-key';
};

export type CreateApiKeyConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Request Timeout
     */
    408: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorResponse;
    /**
     * Bad Gateway
     */
    502: ApiErrorResponse;
    /**
     * Service Unavailable
     */
    503: ApiErrorResponse;
    /**
     * Gateway Timeout
     */
    504: ApiErrorResponse;
};

export type CreateApiKeyConnectionError = CreateApiKeyConnectionErrors[keyof CreateApiKeyConnectionErrors];

export type CreateApiKeyConnectionResponses = {
    /**
     * Created
     */
    201: ApiCreateConnectionResponse;
};

export type CreateApiKeyConnectionResponse = CreateApiKeyConnectionResponses[keyof CreateApiKeyConnectionResponses];

export type BeginOAuthConnectionData = {
    /**
     * alias 为可选展示标签；redirect_url 为授权完成后回跳调用方的地址（可选）
     */
    body: ApiBeginOAuthRequest;
    path?: never;
    query?: never;
    url: '/v1/connections/oauth';
};

export type BeginOAuthConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type BeginOAuthConnectionError = BeginOAuthConnectionErrors[keyof BeginOAuthConnectionErrors];

export type BeginOAuthConnectionResponses = {
    /**
     * Created
     */
    201: ApiBeginOAuthResponse;
};

export type BeginOAuthConnectionResponse = BeginOAuthConnectionResponses[keyof BeginOAuthConnectionResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/v1/connections/{id}';
};

export type DeleteConnectionErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetConnectionData = {
    body?: never;
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/v1/connections/{id}';
};

export type GetConnectionErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type GetConnectionError = GetConnectionErrors[keyof GetConnectionErrors];

export type GetConnectionResponses = {
    /**
     * OK
     */
    200: ConnsvcConnectionView;
};

export type GetConnectionResponse = GetConnectionResponses[keyof GetConnectionResponses];

export type RecredentialConnectionData = {
    /**
     * 完整 credential 字段组；不是局部 PATCH
     */
    body: ApiRecredentialRequest;
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/v1/connections/{id}/credential';
};

export type RecredentialConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Request Timeout
     */
    408: ApiErrorResponse;
    /**
     * Conflict
     */
    409: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorResponse;
    /**
     * Bad Gateway
     */
    502: ApiErrorResponse;
    /**
     * Service Unavailable
     */
    503: ApiErrorResponse;
    /**
     * Gateway Timeout
     */
    504: ApiErrorResponse;
};

export type RecredentialConnectionError = RecredentialConnectionErrors[keyof RecredentialConnectionErrors];

export type RecredentialConnectionResponses = {
    /**
     * OK
     */
    200: ConnsvcConnectionView;
};

export type RecredentialConnectionResponse = RecredentialConnectionResponses[keyof RecredentialConnectionResponses];

export type ReauthConnectionData = {
    /**
     * redirect_url 可选
     */
    body?: ApiReauthRequest;
    path: {
        /**
         * connection id（uuid）
         */
        id: string;
    };
    query?: never;
    url: '/v1/connections/{id}/reauth';
};

export type ReauthConnectionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Not Found
     */
    404: ApiErrorResponse;
    /**
     * Conflict
     */
    409: ApiErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ApiErrorResponse;
};

export type ReauthConnectionError = ReauthConnectionErrors[keyof ReauthConnectionErrors];

export type ReauthConnectionResponses = {
    /**
     * OK
     */
    200: ApiBeginOAuthResponse;
};

export type ReauthConnectionResponse = ReauthConnectionResponses[keyof ReauthConnectionResponses];

export type ListConnectorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/connectors';
};

export type ListConnectorsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
};

export type ListConnectorsError = ListConnectorsErrors[keyof ListConnectorsErrors];

export type ListConnectorsResponses = {
    /**
     * OK
     */
    200: Array<CatalogsvcItem>;
};

export type ListConnectorsResponse = ListConnectorsResponses[keyof ListConnectorsResponses];

export type GetConnectorData = {
    body?: never;
    path: {
        /**
         * connector_type
         */
        type: string;
    };
    query?: never;
    url: '/v1/connectors/{type}';
};

export type GetConnectorErrors = {
    /**
     * Not Found
     */
    404: ApiErrorResponse;
};

export type GetConnectorError = GetConnectorErrors[keyof GetConnectorErrors];

export type GetConnectorResponses = {
    /**
     * OK
     */
    200: CatalogsvcItem;
};

export type GetConnectorResponse = GetConnectorResponses[keyof GetConnectorResponses];

export type CreateMcpSessionData = {
    /**
     * 连接绑定与不可变 grant 快照；省略 allowlist 默认当前 read，[] 为零 Tool，null 拒绝；write/destructive 必须显式列出；ttl_seconds 默认 3600、上限 86400
     */
    body: ApiCreateMcpSessionRequest;
    path?: never;
    query?: never;
    url: '/v1/mcp-sessions';
};

export type CreateMcpSessionErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorResponse;
};

export type CreateMcpSessionError = CreateMcpSessionErrors[keyof CreateMcpSessionErrors];

export type CreateMcpSessionResponses = {
    /**
     * Created
     */
    201: ApiCreateMcpSessionResponse;
};

export type CreateMcpSessionResponse = CreateMcpSessionResponses[keyof CreateMcpSessionResponses];

export type OauthCallbackData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 授权发起时生成的 state
         */
        state?: string;
        /**
         * 授权码
         */
        code?: string;
        /**
         * provider 返回的错误码
         */
        error?: string;
    };
    url: '/v1/oauth/callback';
};
