// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_account.sql

package store

import (
	"context"
)

const getAdminAccount = `-- name: GetAdminAccount :one
SELECT id, username, password_hash, updated_at FROM admin_account WHERE id = 1
`

func (q *Queries) GetAdminAccount(ctx context.Context) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccount)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdminAccountIfAbsent = `-- name: InsertAdminAccountIfAbsent :execrows
INSERT INTO admin_account (id, username, password_hash, updated_at)
VALUES (1, $1, $2, now())
ON CONFLICT (id) DO NOTHING
`

type InsertAdminAccountIfAbsentParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) InsertAdminAccountIfAbsent(ctx context.Context, arg InsertAdminAccountIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAdminAccountIfAbsent, arg.Username, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAdminPassword = `-- name: UpdateAdminPassword :execrows
UPDATE admin_account SET password_hash = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) UpdateAdminPassword(ctx context.Context, passwordHash string) (int64, error) {
	result, err := q.db.Exec(ctx, updateAdminPassword, passwordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
