// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_tokens.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, name, token_hash, created_at, revoked_at FROM api_tokens WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_tokens (id, name, token_hash, created_at)
VALUES ($1, $2, $3, now())
`

type InsertAPITokenParams struct {
	ID        uuid.UUID
	Name      string
	TokenHash string
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.Exec(ctx, insertAPIToken, arg.ID, arg.Name, arg.TokenHash)
	return err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, token_hash, created_at, revoked_at FROM api_tokens ORDER BY created_at DESC
`

func (q *Queries) ListAPITokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
