// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authorization_state.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireRefreshLease = `-- name: AcquireRefreshLease :one

UPDATE connections
SET refresh_owner = $1,
    refresh_lease_until = CURRENT_TIMESTAMP
      + make_interval(secs => $2::int),
    refresh_state = 'leased',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
  AND status = 'active'
  AND authorization_generation = $4
  AND $2 BETWEEN 30 AND 600
  AND (
    refresh_state IS NULL
    OR (
      refresh_state = 'leased'
      AND refresh_lease_until <= CURRENT_TIMESTAMP
    )
  )
RETURNING
  id,
  credential_version,
  authorization_generation,
  refresh_owner,
  refresh_lease_until,
  refresh_state
`

type AcquireRefreshLeaseParams struct {
	Owner                           *uuid.UUID
	LeaseSeconds                    int32
	ConnectionID                    uuid.UUID
	ExpectedAuthorizationGeneration int64
}

type AcquireRefreshLeaseRow struct {
	ID                      uuid.UUID
	CredentialVersion       int64
	AuthorizationGeneration int64
	RefreshOwner            *uuid.UUID
	RefreshLeaseUntil       *time.Time
	RefreshState            *string
}

// Refresh lease primitives. Network I/O happens only after Acquire +
// Read + MarkRequesting have committed.
func (q *Queries) AcquireRefreshLease(ctx context.Context, arg AcquireRefreshLeaseParams) (AcquireRefreshLeaseRow, error) {
	row := q.db.QueryRow(ctx, acquireRefreshLease,
		arg.Owner,
		arg.LeaseSeconds,
		arg.ConnectionID,
		arg.ExpectedAuthorizationGeneration,
	)
	var i AcquireRefreshLeaseRow
	err := row.Scan(
		&i.ID,
		&i.CredentialVersion,
		&i.AuthorizationGeneration,
		&i.RefreshOwner,
		&i.RefreshLeaseUntil,
		&i.RefreshState,
	)
	return i, err
}

const beginInitialOAuthAuthorizationAtPolicyIdentity = `-- name: BeginInitialOAuthAuthorizationAtPolicyIdentity :one
WITH matched_policy AS (
  SELECT policy.connector_type
  FROM connector_policy_identities AS policy
  WHERE policy.connector_type = $1
    AND policy.initialized
    AND policy.identity_version = $2
    AND policy.identity_digest = $3
    AND policy.definition_digest = $4
  FOR SHARE
),
created_connection AS (
  INSERT INTO connections (
    id,
    connector_type,
    alias,
    auth_method,
    credential,
    secret_key_version,
    profile,
    scopes,
    scopes_known,
    status,
    access_token_expires_at,
    credential_version,
    authorization_generation,
    authorization_attempt_version,
    created_at,
    updated_at
  )
  SELECT
    $5,
    $1,
    $6,
    $7,
    $8,
    $9,
    '{}'::jsonb,
    $10,
    false,
    'pending',
    NULL,
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  FROM matched_policy
  RETURNING
    id,
    authorization_attempt_version,
    authorization_generation
),
created_authorization AS (
  INSERT INTO oauth_authorizations (
    id,
    connector_type,
    state_hash,
    context_ciphertext,
    context_version,
    connection_id,
    status,
    expires_at,
    created_at,
    auth_method,
    alias,
    secret_key_version,
    redirect_url,
    attempt_version,
    expected_authorization_generation,
    flow_kind,
    requested_scopes
  )
  SELECT
    $11,
    $1,
    $12,
    $13,
    1,
    c.id,
    'pending',
    $14,
    CURRENT_TIMESTAMP,
    $7,
    COALESCE($6::text, ''),
    $15,
    $16,
    c.authorization_attempt_version,
    c.authorization_generation,
    'initial',
    $10
  FROM created_connection AS c
  RETURNING
    id,
    connection_id,
    attempt_version,
    expected_authorization_generation
)
SELECT
  a.connection_id,
  a.id AS authorization_id,
  a.attempt_version,
  a.expected_authorization_generation
FROM created_authorization AS a
`

type BeginInitialOAuthAuthorizationAtPolicyIdentityParams struct {
	ConnectorType                 string
	ExpectedIdentityVersion       int32
	ExpectedIdentityDigest        []byte
	ExpectedDefinitionDigest      []byte
	ConnectionID                  uuid.UUID
	ConnectionAlias               *string
	AuthMethod                    string
	EmptyCredential               []byte
	ConnectionSecretKeyVersion    int32
	RequestedScopes               []string
	AuthorizationID               uuid.UUID
	StateHash                     string
	ContextCiphertext             []byte
	ExpiresAt                     time.Time
	AuthorizationSecretKeyVersion int32
	RedirectUrl                   string
}

type BeginInitialOAuthAuthorizationAtPolicyIdentityRow struct {
	ConnectionID                    uuid.UUID
	AuthorizationID                 uuid.UUID
	AttemptVersion                  int64
	ExpectedAuthorizationGeneration int64
}

// Initial authorization preparation may perform inbound verification and
// build a provider URL before touching the database. Bind its insert to the
// exact connector policy used for that work. The shared row lock has the same
// ordering guarantee as CreateConnectionAtPolicyIdentity.
func (q *Queries) BeginInitialOAuthAuthorizationAtPolicyIdentity(ctx context.Context, arg BeginInitialOAuthAuthorizationAtPolicyIdentityParams) (BeginInitialOAuthAuthorizationAtPolicyIdentityRow, error) {
	row := q.db.QueryRow(ctx, beginInitialOAuthAuthorizationAtPolicyIdentity,
		arg.ConnectorType,
		arg.ExpectedIdentityVersion,
		arg.ExpectedIdentityDigest,
		arg.ExpectedDefinitionDigest,
		arg.ConnectionID,
		arg.ConnectionAlias,
		arg.AuthMethod,
		arg.EmptyCredential,
		arg.ConnectionSecretKeyVersion,
		arg.RequestedScopes,
		arg.AuthorizationID,
		arg.StateHash,
		arg.ContextCiphertext,
		arg.ExpiresAt,
		arg.AuthorizationSecretKeyVersion,
		arg.RedirectUrl,
	)
	var i BeginInitialOAuthAuthorizationAtPolicyIdentityRow
	err := row.Scan(
		&i.ConnectionID,
		&i.AuthorizationID,
		&i.AttemptVersion,
		&i.ExpectedAuthorizationGeneration,
	)
	return i, err
}

const beginOAuthReauthorization = `-- name: BeginOAuthReauthorization :one
WITH bumped_connection AS (
  UPDATE connections AS target
  SET authorization_attempt_version = authorization_attempt_version + 1,
      authorization_generation = authorization_generation + 1,
      updated_at = CURRENT_TIMESTAMP
  WHERE target.id = $1
    AND target.status IN ('active', 'reauth_required')
    AND target.authorization_attempt_version =
        $2
    AND target.authorization_generation =
        $3
  RETURNING
    target.id,
    target.connector_type,
    target.auth_method,
    COALESCE(target.alias, '') AS authorization_alias,
    target.authorization_attempt_version,
    target.authorization_generation
),
created_authorization AS (
  INSERT INTO oauth_authorizations (
    id,
    connector_type,
    state_hash,
    context_ciphertext,
    context_version,
    connection_id,
    status,
    expires_at,
    created_at,
    auth_method,
    alias,
    secret_key_version,
    redirect_url,
    attempt_version,
    expected_authorization_generation,
    flow_kind,
    requested_scopes
  )
  SELECT
    $4,
    c.connector_type,
    $5,
    $6,
    1,
    c.id,
    'pending',
    $7,
    CURRENT_TIMESTAMP,
    c.auth_method,
    c.authorization_alias,
    $8,
    $9,
    c.authorization_attempt_version,
    c.authorization_generation,
    'reauth',
    $10
  FROM bumped_connection AS c
  RETURNING
    id,
    connection_id,
    attempt_version,
    expected_authorization_generation
)
SELECT
  a.connection_id,
  a.id AS authorization_id,
  a.attempt_version,
  a.expected_authorization_generation
FROM created_authorization AS a
`

type BeginOAuthReauthorizationParams struct {
	ConnectionID                           uuid.UUID
	ExpectedCurrentAttemptVersion          int64
	ExpectedCurrentAuthorizationGeneration int64
	AuthorizationID                        uuid.UUID
	StateHash                              string
	ContextCiphertext                      []byte
	ExpiresAt                              time.Time
	AuthorizationSecretKeyVersion          int32
	RedirectUrl                            string
	RequestedScopes                        []string
}

type BeginOAuthReauthorizationRow struct {
	ConnectionID                    uuid.UUID
	AuthorizationID                 uuid.UUID
	AttemptVersion                  int64
	ExpectedAuthorizationGeneration int64
}

// A new reauth attempt immediately supersedes older attempts by advancing
// both the attempt and authorization generation before inserting its row.
func (q *Queries) BeginOAuthReauthorization(ctx context.Context, arg BeginOAuthReauthorizationParams) (BeginOAuthReauthorizationRow, error) {
	row := q.db.QueryRow(ctx, beginOAuthReauthorization,
		arg.ConnectionID,
		arg.ExpectedCurrentAttemptVersion,
		arg.ExpectedCurrentAuthorizationGeneration,
		arg.AuthorizationID,
		arg.StateHash,
		arg.ContextCiphertext,
		arg.ExpiresAt,
		arg.AuthorizationSecretKeyVersion,
		arg.RedirectUrl,
		arg.RequestedScopes,
	)
	var i BeginOAuthReauthorizationRow
	err := row.Scan(
		&i.ConnectionID,
		&i.AuthorizationID,
		&i.AttemptVersion,
		&i.ExpectedAuthorizationGeneration,
	)
	return i, err
}

const claimOAuthAuthorization = `-- name: ClaimOAuthAuthorization :one
UPDATE oauth_authorizations AS a
SET status = 'claimed'
FROM connections AS c
WHERE a.state_hash = $1
  AND a.status = 'pending'
  AND a.expires_at > CURRENT_TIMESTAMP
  AND c.id = a.connection_id
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
  AND (
    (a.flow_kind = 'initial' AND c.status = 'pending')
    OR
    (a.flow_kind = 'reauth' AND c.status IN ('active', 'reauth_required'))
  )
RETURNING a.id, a.connector_type, a.state_hash, a.context_ciphertext, a.connection_id, a.status, a.expires_at, a.created_at, a.auth_method, a.alias, a.secret_key_version, a.redirect_url, a.attempt_version, a.expected_authorization_generation, a.flow_kind, a.requested_scopes, a.context_version
`

// Claim is the only transition that permits network token exchange. It uses
// database time and current Connection attempt/generation state.
func (q *Queries) ClaimOAuthAuthorization(ctx context.Context, stateHash string) (OauthAuthorization, error) {
	row := q.db.QueryRow(ctx, claimOAuthAuthorization, stateHash)
	var i OauthAuthorization
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.StateHash,
		&i.ContextCiphertext,
		&i.ConnectionID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AuthMethod,
		&i.Alias,
		&i.SecretKeyVersion,
		&i.RedirectUrl,
		&i.AttemptVersion,
		&i.ExpectedAuthorizationGeneration,
		&i.FlowKind,
		&i.RequestedScopes,
		&i.ContextVersion,
	)
	return i, err
}

const cleanupExpiredInitialOAuthAuthorizations = `-- name: CleanupExpiredInitialOAuthAuthorizations :execrows
DELETE FROM connections AS c
USING oauth_authorizations AS a
WHERE a.flow_kind = 'initial'
  AND a.status = 'pending'
  AND a.expires_at <= CURRENT_TIMESTAMP
  AND c.id = a.connection_id
  AND c.status = 'pending'
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
`

func (q *Queries) CleanupExpiredInitialOAuthAuthorizations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredInitialOAuthAuthorizations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupInitialOAuthAuthorization = `-- name: CleanupInitialOAuthAuthorization :execrows
DELETE FROM connections AS c
USING oauth_authorizations AS a
WHERE a.id = $1
  AND a.flow_kind = 'initial'
  AND a.status IN ('pending', 'claimed')
  AND c.id = a.connection_id
  AND c.status = 'pending'
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
`

// Initial failures/expiry remove only the still-matching pending Connection;
// the authorization is removed by the FK cascade.
func (q *Queries) CleanupInitialOAuthAuthorization(ctx context.Context, authorizationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupInitialOAuthAuthorization, authorizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupStaleClaimedInitialOAuthAuthorizations = `-- name: CleanupStaleClaimedInitialOAuthAuthorizations :execrows
DELETE FROM connections AS c
USING oauth_authorizations AS a
WHERE a.flow_kind = 'initial'
  AND a.status = 'claimed'
  AND $1::integer BETWEEN 60 AND 600
  AND a.expires_at
      + make_interval(secs => $1::int)
      <= CURRENT_TIMESTAMP
  AND c.id = a.connection_id
  AND c.status = 'pending'
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
`

// A callback claimed immediately before expires_at is allowed to finish.
// Only recover a crashed/abandoned claim after a fixed caller-supplied grace
// which must be wider than the bounded token-exchange + validator window.
// The Connection version predicates fence this janitor from newer attempts.
func (q *Queries) CleanupStaleClaimedInitialOAuthAuthorizations(ctx context.Context, recoveryGraceSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupStaleClaimedInitialOAuthAuthorizations, recoveryGraceSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupSupersededInitialOAuthAuthorizations = `-- name: CleanupSupersededInitialOAuthAuthorizations :execrows
DELETE FROM connections AS c
USING oauth_authorizations AS a
WHERE a.connection_id = c.id
  AND a.flow_kind = 'initial'
  AND a.status = 'superseded'
  AND c.status = 'pending'
  AND c.authorization_attempt_version = a.attempt_version
  AND NOT EXISTS (
    SELECT 1
    FROM oauth_authorizations AS current_attempt
    WHERE current_attempt.connection_id = c.id
      AND current_attempt.status IN ('pending', 'claimed')
      AND current_attempt.attempt_version =
          c.authorization_attempt_version
      AND current_attempt.expected_authorization_generation =
          c.authorization_generation
  )
`

// A policy/config generation bump may supersede an already claimed initial
// attempt. Initial Connections cannot start a newer flow while pending, so
// the unchanged attempt_version plus absence of a current live authorization
// safely identifies the otherwise orphaned pending Connection. Generation is
// intentionally not compared: its drift is why this row was superseded.
func (q *Queries) CleanupSupersededInitialOAuthAuthorizations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupSupersededInitialOAuthAuthorizations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearRefreshLeaseCAS = `-- name: ClearRefreshLeaseCAS :execrows
UPDATE connections
SET refresh_owner = NULL,
    refresh_lease_until = NULL,
    refresh_state = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND refresh_owner = $2
  AND refresh_state = $3
  AND credential_version = $4
  AND authorization_generation = $5
`

type ClearRefreshLeaseCASParams struct {
	ConnectionID                    uuid.UUID
	Owner                           *uuid.UUID
	ExpectedRefreshState            *string
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

// Only use this when the caller can prove no Provider request was sent or a
// definitive protocol response proves that no token was issued/rotated.
func (q *Queries) ClearRefreshLeaseCAS(ctx context.Context, arg ClearRefreshLeaseCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRefreshLeaseCAS,
		arg.ConnectionID,
		arg.Owner,
		arg.ExpectedRefreshState,
		arg.ExpectedCredentialVersion,
		arg.ExpectedAuthorizationGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeOAuthAuthorizationCAS = `-- name: CompleteOAuthAuthorizationCAS :one
WITH candidate AS MATERIALIZED (
  SELECT
    a.id,
    a.connection_id,
    a.attempt_version,
    a.expected_authorization_generation,
    a.flow_kind
  FROM oauth_authorizations AS a
  WHERE a.id = $1
    AND a.status = 'claimed'
  FOR UPDATE
),
updated_connection AS (
  UPDATE connections AS c
  SET credential = $2,
      secret_key_version = $3,
      profile = $4,
      scopes = $5,
      scopes_known = $6,
      status = 'active',
      access_token_expires_at = $7,
      credential_version = c.credential_version + 1,
      authorization_generation = c.authorization_generation + 1,
      refresh_owner = NULL,
      refresh_lease_until = NULL,
      refresh_state = NULL,
      updated_at = CURRENT_TIMESTAMP
  FROM candidate AS a
  WHERE c.id = a.connection_id
    AND c.authorization_attempt_version = a.attempt_version
    AND c.authorization_generation = a.expected_authorization_generation
    AND (
      (a.flow_kind = 'initial' AND c.status = 'pending')
      OR
      (a.flow_kind = 'reauth' AND c.status IN ('active', 'reauth_required'))
    )
  RETURNING
    c.id AS connection_id,
    c.credential_version,
    c.authorization_generation,
    a.id AS authorization_id
),
completed_authorization AS (
  UPDATE oauth_authorizations AS a
  SET status = 'completed'
  FROM updated_connection AS c
  WHERE a.id = c.authorization_id
    AND a.status = 'claimed'
  RETURNING a.id
)
SELECT
  c.connection_id,
  c.credential_version,
  c.authorization_generation
FROM updated_connection AS c
JOIN completed_authorization AS a
  ON a.id = c.authorization_id
`

type CompleteOAuthAuthorizationCASParams struct {
	AuthorizationID      uuid.UUID
	Credential           []byte
	SecretKeyVersion     int32
	Profile              []byte
	Scopes               []string
	ScopesKnown          bool
	AccessTokenExpiresAt *time.Time
}

type CompleteOAuthAuthorizationCASRow struct {
	ConnectionID            uuid.UUID
	CredentialVersion       int64
	AuthorizationGeneration int64
}

// OAuth completion updates the entire Connection credential snapshot and
// marks the claimed authorization completed in the same statement. It does
// not compare credential_version: a token-only refresh may finish during a
// browser reauth flow. Completion advances authorization_generation again:
// Begin already exposed a new generation while the old credential remained,
// so any Session created in that interval must be invalidated once the new
// credential/account snapshot commits.
func (q *Queries) CompleteOAuthAuthorizationCAS(ctx context.Context, arg CompleteOAuthAuthorizationCASParams) (CompleteOAuthAuthorizationCASRow, error) {
	row := q.db.QueryRow(ctx, completeOAuthAuthorizationCAS,
		arg.AuthorizationID,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.Profile,
		arg.Scopes,
		arg.ScopesKnown,
		arg.AccessTokenExpiresAt,
	)
	var i CompleteOAuthAuthorizationCASRow
	err := row.Scan(&i.ConnectionID, &i.CredentialVersion, &i.AuthorizationGeneration)
	return i, err
}

const completeRefreshLeaseCAS = `-- name: CompleteRefreshLeaseCAS :one
UPDATE connections
SET credential = $1,
    secret_key_version = $2,
    scopes = $3,
    scopes_known = $4,
    status = 'active',
    access_token_expires_at = $5,
    credential_version = credential_version + 1,
    authorization_generation = authorization_generation
      + CASE WHEN $6::boolean THEN 1 ELSE 0 END,
    refresh_owner = NULL,
    refresh_lease_until = NULL,
    refresh_state = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
  AND refresh_owner = $8
  AND refresh_state = 'requesting'
  AND credential_version = $9
  AND authorization_generation = $10
RETURNING id, credential_version, authorization_generation
`

type CompleteRefreshLeaseCASParams struct {
	Credential                      []byte
	SecretKeyVersion                int32
	Scopes                          []string
	ScopesKnown                     bool
	AccessTokenExpiresAt            *time.Time
	AuthorizationFactsChanged       bool
	ConnectionID                    uuid.UUID
	Owner                           *uuid.UUID
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

type CompleteRefreshLeaseCASRow struct {
	ID                      uuid.UUID
	CredentialVersion       int64
	AuthorizationGeneration int64
}

func (q *Queries) CompleteRefreshLeaseCAS(ctx context.Context, arg CompleteRefreshLeaseCASParams) (CompleteRefreshLeaseCASRow, error) {
	row := q.db.QueryRow(ctx, completeRefreshLeaseCAS,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.Scopes,
		arg.ScopesKnown,
		arg.AccessTokenExpiresAt,
		arg.AuthorizationFactsChanged,
		arg.ConnectionID,
		arg.Owner,
		arg.ExpectedCredentialVersion,
		arg.ExpectedAuthorizationGeneration,
	)
	var i CompleteRefreshLeaseCASRow
	err := row.Scan(&i.ID, &i.CredentialVersion, &i.AuthorizationGeneration)
	return i, err
}

const expireReauthOAuthAuthorizations = `-- name: ExpireReauthOAuthAuthorizations :execrows
UPDATE oauth_authorizations AS a
SET status = 'expired'
FROM connections AS c
WHERE a.flow_kind = 'reauth'
  AND a.status = 'pending'
  AND a.expires_at <= CURRENT_TIMESTAMP
  AND c.id = a.connection_id
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
`

func (q *Queries) ExpireReauthOAuthAuthorizations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireReauthOAuthAuthorizations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStaleClaimedReauthOAuthAuthorizations = `-- name: ExpireStaleClaimedReauthOAuthAuthorizations :execrows
UPDATE oauth_authorizations AS a
SET status = 'expired'
FROM connections AS c
WHERE a.flow_kind = 'reauth'
  AND a.status = 'claimed'
  AND $1::integer BETWEEN 60 AND 600
  AND a.expires_at
      + make_interval(secs => $1::int)
      <= CURRENT_TIMESTAMP
  AND c.id = a.connection_id
  AND c.status IN ('active', 'reauth_required')
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
`

// Claimed reauth callbacks get the same recovery grace as initial callbacks.
// Recovery only closes the matching attempt and never changes the active
// Connection or its credential.
func (q *Queries) ExpireStaleClaimedReauthOAuthAuthorizations(ctx context.Context, recoveryGraceSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleClaimedReauthOAuthAuthorizations, recoveryGraceSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failReauthOAuthAuthorization = `-- name: FailReauthOAuthAuthorization :execrows
UPDATE oauth_authorizations AS a
SET status = 'failed'
FROM connections AS c
WHERE a.id = $1
  AND a.flow_kind = 'reauth'
  AND a.status IN ('pending', 'claimed')
  AND c.id = a.connection_id
  AND c.authorization_attempt_version = a.attempt_version
  AND c.authorization_generation = a.expected_authorization_generation
`

// Reauth failure ends only the attempt; it never deletes or downgrades the
// active Connection.
func (q *Queries) FailReauthOAuthAuthorization(ctx context.Context, authorizationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, failReauthOAuthAuthorization, authorizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectionAtAuthorizationGeneration = `-- name: GetConnectionAtAuthorizationGeneration :one

SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, created_at, updated_at, authorization_generation, scopes_known, credential_version, authorization_attempt_version, refresh_owner, refresh_lease_until, refresh_state
FROM connections
WHERE id = $1
  AND authorization_generation = $2
`

type GetConnectionAtAuthorizationGenerationParams struct {
	ConnectionID                    uuid.UUID
	ExpectedAuthorizationGeneration int64
}

// Connection credential/authorization version primitives.
func (q *Queries) GetConnectionAtAuthorizationGeneration(ctx context.Context, arg GetConnectionAtAuthorizationGenerationParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionAtAuthorizationGeneration, arg.ConnectionID, arg.ExpectedAuthorizationGeneration)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationGeneration,
		&i.ScopesKnown,
		&i.CredentialVersion,
		&i.AuthorizationAttemptVersion,
		&i.RefreshOwner,
		&i.RefreshLeaseUntil,
		&i.RefreshState,
	)
	return i, err
}

const getRefreshLeaseCredential = `-- name: GetRefreshLeaseCredential :one
SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, created_at, updated_at, authorization_generation, scopes_known, credential_version, authorization_attempt_version, refresh_owner, refresh_lease_until, refresh_state
FROM connections
WHERE id = $1
  AND refresh_owner = $2
  AND refresh_state IN ('leased', 'requesting')
  AND refresh_lease_until > CURRENT_TIMESTAMP
  AND credential_version = $3
  AND authorization_generation = $4
`

type GetRefreshLeaseCredentialParams struct {
	ConnectionID                    uuid.UUID
	Owner                           *uuid.UUID
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

func (q *Queries) GetRefreshLeaseCredential(ctx context.Context, arg GetRefreshLeaseCredentialParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getRefreshLeaseCredential,
		arg.ConnectionID,
		arg.Owner,
		arg.ExpectedCredentialVersion,
		arg.ExpectedAuthorizationGeneration,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationGeneration,
		&i.ScopesKnown,
		&i.CredentialVersion,
		&i.AuthorizationAttemptVersion,
		&i.RefreshOwner,
		&i.RefreshLeaseUntil,
		&i.RefreshState,
	)
	return i, err
}

const markConnectionCredentialInvalidCAS = `-- name: MarkConnectionCredentialInvalidCAS :execrows
UPDATE connections
SET status = 'reauth_required',
    refresh_owner = NULL,
    refresh_lease_until = NULL,
    refresh_state = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND status = 'active'
  AND credential_version = $2
  AND authorization_generation = $3
`

type MarkConnectionCredentialInvalidCASParams struct {
	ConnectionID                    uuid.UUID
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

// A backend may mark an active Connection reauth_required only after a
// definitive credential-invalid response for the exact credential snapshot it
// used. A stale response must not mutate a newer credential or authorization
// generation.
func (q *Queries) MarkConnectionCredentialInvalidCAS(ctx context.Context, arg MarkConnectionCredentialInvalidCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectionCredentialInvalidCAS, arg.ConnectionID, arg.ExpectedCredentialVersion, arg.ExpectedAuthorizationGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRefreshLeaseReauthRequiredCAS = `-- name: MarkRefreshLeaseReauthRequiredCAS :execrows
UPDATE connections
SET status = 'reauth_required',
    refresh_owner = NULL,
    refresh_lease_until = NULL,
    refresh_state = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND refresh_owner = $2
  AND refresh_state = $3
  AND credential_version = $4
  AND authorization_generation = $5
`

type MarkRefreshLeaseReauthRequiredCASParams struct {
	ConnectionID                    uuid.UUID
	Owner                           *uuid.UUID
	ExpectedRefreshState            *string
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

// A definitive credential-invalid outcome for this exact lease: either an
// invalid_grant answer to the requesting exchange, or an expired credential
// with no refresh token, found while the lease is still merely leased. The
// caller names the state it observed so a lease in the other state is fenced.
func (q *Queries) MarkRefreshLeaseReauthRequiredCAS(ctx context.Context, arg MarkRefreshLeaseReauthRequiredCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshLeaseReauthRequiredCAS,
		arg.ConnectionID,
		arg.Owner,
		arg.ExpectedRefreshState,
		arg.ExpectedCredentialVersion,
		arg.ExpectedAuthorizationGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRefreshLeaseRequesting = `-- name: MarkRefreshLeaseRequesting :one
UPDATE connections
SET refresh_state = 'requesting',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND refresh_owner = $2
  AND refresh_state = 'leased'
  AND refresh_lease_until > CURRENT_TIMESTAMP
  AND credential_version = $3
  AND authorization_generation = $4
RETURNING refresh_lease_until
`

type MarkRefreshLeaseRequestingParams struct {
	ConnectionID                    uuid.UUID
	Owner                           *uuid.UUID
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

func (q *Queries) MarkRefreshLeaseRequesting(ctx context.Context, arg MarkRefreshLeaseRequestingParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, markRefreshLeaseRequesting,
		arg.ConnectionID,
		arg.Owner,
		arg.ExpectedCredentialVersion,
		arg.ExpectedAuthorizationGeneration,
	)
	var refresh_lease_until *time.Time
	err := row.Scan(&refresh_lease_until)
	return refresh_lease_until, err
}

const markSupersededOAuthAuthorizations = `-- name: MarkSupersededOAuthAuthorizations :execrows
UPDATE oauth_authorizations AS a
SET status = 'superseded'
FROM connections AS c
WHERE a.connection_id = c.id
  AND a.status IN ('pending', 'claimed')
  AND (
    a.attempt_version <> c.authorization_attempt_version
    OR
    a.expected_authorization_generation <> c.authorization_generation
  )
`

func (q *Queries) MarkSupersededOAuthAuthorizations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markSupersededOAuthAuthorizations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recredentialConnection = `-- name: RecredentialConnection :one
UPDATE connections
SET credential = $1,
    secret_key_version = $2,
    profile = $3,
    scopes = $4,
    scopes_known = $5,
    status = 'active',
    access_token_expires_at = $6,
    credential_version = credential_version + 1,
    authorization_generation = authorization_generation + 1,
    refresh_owner = NULL,
    refresh_lease_until = NULL,
    refresh_state = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
  AND credential_version = $8
  AND authorization_generation = $9
  AND status <> 'pending'
RETURNING id, credential_version, authorization_generation
`

type RecredentialConnectionParams struct {
	Credential                      []byte
	SecretKeyVersion                int32
	Profile                         []byte
	Scopes                          []string
	ScopesKnown                     bool
	AccessTokenExpiresAt            *time.Time
	ConnectionID                    uuid.UUID
	ExpectedCredentialVersion       int64
	ExpectedAuthorizationGeneration int64
}

type RecredentialConnectionRow struct {
	ID                      uuid.UUID
	CredentialVersion       int64
	AuthorizationGeneration int64
}

func (q *Queries) RecredentialConnection(ctx context.Context, arg RecredentialConnectionParams) (RecredentialConnectionRow, error) {
	row := q.db.QueryRow(ctx, recredentialConnection,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.Profile,
		arg.Scopes,
		arg.ScopesKnown,
		arg.AccessTokenExpiresAt,
		arg.ConnectionID,
		arg.ExpectedCredentialVersion,
		arg.ExpectedAuthorizationGeneration,
	)
	var i RecredentialConnectionRow
	err := row.Scan(&i.ID, &i.CredentialVersion, &i.AuthorizationGeneration)
	return i, err
}

const resolveExpiredRequestingRefreshLeases = `-- name: ResolveExpiredRequestingRefreshLeases :execrows
UPDATE connections
SET status = 'reauth_required',
    refresh_owner = NULL,
    refresh_lease_until = NULL,
    refresh_state = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'active'
  AND refresh_state = 'requesting'
  AND refresh_lease_until <= CURRENT_TIMESTAMP
`

// Default no-replay policy: an expired lease that may have reached the
// Provider becomes reauth_required instead of replaying a rotating token.
func (q *Queries) ResolveExpiredRequestingRefreshLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resolveExpiredRequestingRefreshLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
