// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: configs.sql

package store

import (
	"context"
	"time"
)

const deleteConnectorConfig = `-- name: DeleteConnectorConfig :execrows
DELETE FROM connector_configs WHERE connector_type = $1
`

func (q *Queries) DeleteConnectorConfig(ctx context.Context, connectorType string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectorConfig, connectorType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectorConfig = `-- name: GetConnectorConfig :one
SELECT connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at FROM connector_configs WHERE connector_type = $1
`

func (q *Queries) GetConnectorConfig(ctx context.Context, connectorType string) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, getConnectorConfig, connectorType)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorConfigs = `-- name: ListConnectorConfigs :many
SELECT connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at FROM connector_configs ORDER BY connector_type
`

func (q *Queries) ListConnectorConfigs(ctx context.Context) ([]ConnectorConfig, error) {
	rows, err := q.db.Query(ctx, listConnectorConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectorConfig
	for rows.Next() {
		var i ConnectorConfig
		if err := rows.Scan(
			&i.ConnectorType,
			&i.ConfigSchemaVersion,
			&i.PublicConfig,
			&i.SecretConfig,
			&i.SecretKeyVersion,
			&i.McpVerifiedEndpoint,
			&i.McpVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectorConfigIfMatch = `-- name: UpdateConnectorConfigIfMatch :one
UPDATE connector_configs SET
  config_schema_version = $2,
  public_config = $3,
  secret_config = $4,
  secret_key_version = $5,
  updated_at = now()
WHERE connector_type = $1 AND updated_at = $6
RETURNING connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at
`

type UpdateConnectorConfigIfMatchParams struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
	UpdatedAt           time.Time
}

func (q *Queries) UpdateConnectorConfigIfMatch(ctx context.Context, arg UpdateConnectorConfigIfMatchParams) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, updateConnectorConfigIfMatch,
		arg.ConnectorType,
		arg.ConfigSchemaVersion,
		arg.PublicConfig,
		arg.SecretConfig,
		arg.SecretKeyVersion,
		arg.UpdatedAt,
	)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnectorConfig = `-- name: UpsertConnectorConfig :one
INSERT INTO connector_configs (
  connector_type, config_schema_version, public_config, secret_config,
  secret_key_version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (connector_type) DO UPDATE SET
  config_schema_version = EXCLUDED.config_schema_version,
  public_config = EXCLUDED.public_config,
  secret_config = EXCLUDED.secret_config,
  secret_key_version = EXCLUDED.secret_key_version,
  updated_at = now()
RETURNING connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at
`

type UpsertConnectorConfigParams struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
}

func (q *Queries) UpsertConnectorConfig(ctx context.Context, arg UpsertConnectorConfigParams) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, upsertConnectorConfig,
		arg.ConnectorType,
		arg.ConfigSchemaVersion,
		arg.PublicConfig,
		arg.SecretConfig,
		arg.SecretKeyVersion,
	)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
