// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: configs.sql

package store

import (
	"context"
	"time"
)

const bumpConnectorAuthorizationGenerations = `-- name: BumpConnectorAuthorizationGenerations :execrows
UPDATE connections
SET authorization_generation = authorization_generation + 1,
    updated_at = now()
WHERE connector_type = $1
`

func (q *Queries) BumpConnectorAuthorizationGenerations(ctx context.Context, connectorType string) (int64, error) {
	result, err := q.db.Exec(ctx, bumpConnectorAuthorizationGenerations, connectorType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearConnectorConfigVerification = `-- name: ClearConnectorConfigVerification :exec
UPDATE connector_configs
SET mcp_verified_endpoint = null,
    mcp_verified_at = null
WHERE connector_type = $1
`

func (q *Queries) ClearConnectorConfigVerification(ctx context.Context, connectorType string) error {
	_, err := q.db.Exec(ctx, clearConnectorConfigVerification, connectorType)
	return err
}

const createConnectorConfig = `-- name: CreateConnectorConfig :one
INSERT INTO connector_configs (
  connector_type, config_schema_version, public_config, secret_config,
  secret_key_version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at
`

type CreateConnectorConfigParams struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
}

func (q *Queries) CreateConnectorConfig(ctx context.Context, arg CreateConnectorConfigParams) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, createConnectorConfig,
		arg.ConnectorType,
		arg.ConfigSchemaVersion,
		arg.PublicConfig,
		arg.SecretConfig,
		arg.SecretKeyVersion,
	)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnectorConfigIfMatch = `-- name: DeleteConnectorConfigIfMatch :execrows
DELETE FROM connector_configs
WHERE connector_type = $1 AND updated_at = $2
`

type DeleteConnectorConfigIfMatchParams struct {
	ConnectorType string
	UpdatedAt     time.Time
}

func (q *Queries) DeleteConnectorConfigIfMatch(ctx context.Context, arg DeleteConnectorConfigIfMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectorConfigIfMatch, arg.ConnectorType, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureConnectorPolicyIdentity = `-- name: EnsureConnectorPolicyIdentity :exec
INSERT INTO connector_policy_identities (
  connector_type, identity_version, identity_digest, definition_digest,
  initialized, created_at, updated_at
) VALUES ($1, $2, '\x'::bytea, '\x'::bytea, false, now(), now())
ON CONFLICT (connector_type) DO NOTHING
`

type EnsureConnectorPolicyIdentityParams struct {
	ConnectorType   string
	IdentityVersion int32
}

func (q *Queries) EnsureConnectorPolicyIdentity(ctx context.Context, arg EnsureConnectorPolicyIdentityParams) error {
	_, err := q.db.Exec(ctx, ensureConnectorPolicyIdentity, arg.ConnectorType, arg.IdentityVersion)
	return err
}

const getConnectorConfig = `-- name: GetConnectorConfig :one
SELECT connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at FROM connector_configs WHERE connector_type = $1
`

func (q *Queries) GetConnectorConfig(ctx context.Context, connectorType string) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, getConnectorConfig, connectorType)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorConfigForUpdate = `-- name: GetConnectorConfigForUpdate :one
SELECT connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at FROM connector_configs WHERE connector_type = $1 FOR UPDATE
`

func (q *Queries) GetConnectorConfigForUpdate(ctx context.Context, connectorType string) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, getConnectorConfigForUpdate, connectorType)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorPolicyIdentity = `-- name: GetConnectorPolicyIdentity :one
SELECT connector_type, identity_version, identity_digest, definition_digest, initialized, created_at, updated_at FROM connector_policy_identities
WHERE connector_type = $1
`

func (q *Queries) GetConnectorPolicyIdentity(ctx context.Context, connectorType string) (ConnectorPolicyIdentity, error) {
	row := q.db.QueryRow(ctx, getConnectorPolicyIdentity, connectorType)
	var i ConnectorPolicyIdentity
	err := row.Scan(
		&i.ConnectorType,
		&i.IdentityVersion,
		&i.IdentityDigest,
		&i.DefinitionDigest,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorPolicyIdentityForUpdate = `-- name: GetConnectorPolicyIdentityForUpdate :one
SELECT connector_type, identity_version, identity_digest, definition_digest, initialized, created_at, updated_at FROM connector_policy_identities
WHERE connector_type = $1
FOR UPDATE
`

func (q *Queries) GetConnectorPolicyIdentityForUpdate(ctx context.Context, connectorType string) (ConnectorPolicyIdentity, error) {
	row := q.db.QueryRow(ctx, getConnectorPolicyIdentityForUpdate, connectorType)
	var i ConnectorPolicyIdentity
	err := row.Scan(
		&i.ConnectorType,
		&i.IdentityVersion,
		&i.IdentityDigest,
		&i.DefinitionDigest,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorConfigs = `-- name: ListConnectorConfigs :many
SELECT connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at FROM connector_configs ORDER BY connector_type
`

func (q *Queries) ListConnectorConfigs(ctx context.Context) ([]ConnectorConfig, error) {
	rows, err := q.db.Query(ctx, listConnectorConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectorConfig
	for rows.Next() {
		var i ConnectorConfig
		if err := rows.Scan(
			&i.ConnectorType,
			&i.ConfigSchemaVersion,
			&i.PublicConfig,
			&i.SecretConfig,
			&i.SecretKeyVersion,
			&i.McpVerifiedEndpoint,
			&i.McpVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectorPolicyIdentity = `-- name: SetConnectorPolicyIdentity :one
UPDATE connector_policy_identities
SET identity_version = $2,
    identity_digest = $3,
    definition_digest = $4,
    initialized = true,
    updated_at = now()
WHERE connector_type = $1
RETURNING connector_type, identity_version, identity_digest, definition_digest, initialized, created_at, updated_at
`

type SetConnectorPolicyIdentityParams struct {
	ConnectorType    string
	IdentityVersion  int32
	IdentityDigest   []byte
	DefinitionDigest []byte
}

func (q *Queries) SetConnectorPolicyIdentity(ctx context.Context, arg SetConnectorPolicyIdentityParams) (ConnectorPolicyIdentity, error) {
	row := q.db.QueryRow(ctx, setConnectorPolicyIdentity,
		arg.ConnectorType,
		arg.IdentityVersion,
		arg.IdentityDigest,
		arg.DefinitionDigest,
	)
	var i ConnectorPolicyIdentity
	err := row.Scan(
		&i.ConnectorType,
		&i.IdentityVersion,
		&i.IdentityDigest,
		&i.DefinitionDigest,
		&i.Initialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectorConfigIfMatch = `-- name: UpdateConnectorConfigIfMatch :one
UPDATE connector_configs SET
  config_schema_version = $2,
  public_config = $3,
  secret_config = $4,
  secret_key_version = $5,
  updated_at = now()
WHERE connector_type = $1 AND updated_at = $6
RETURNING connector_type, config_schema_version, public_config, secret_config, secret_key_version, mcp_verified_endpoint, mcp_verified_at, created_at, updated_at
`

type UpdateConnectorConfigIfMatchParams struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
	UpdatedAt           time.Time
}

func (q *Queries) UpdateConnectorConfigIfMatch(ctx context.Context, arg UpdateConnectorConfigIfMatchParams) (ConnectorConfig, error) {
	row := q.db.QueryRow(ctx, updateConnectorConfigIfMatch,
		arg.ConnectorType,
		arg.ConfigSchemaVersion,
		arg.PublicConfig,
		arg.SecretConfig,
		arg.SecretKeyVersion,
		arg.UpdatedAt,
	)
	var i ConnectorConfig
	err := row.Scan(
		&i.ConnectorType,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretConfig,
		&i.SecretKeyVersion,
		&i.McpVerifiedEndpoint,
		&i.McpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
