// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: connector_settings.sql

package store

import (
	"context"
)

const getConnectorEnabled = `-- name: GetConnectorEnabled :one
SELECT enabled FROM connector_settings WHERE connector_type = $1
`

func (q *Queries) GetConnectorEnabled(ctx context.Context, connectorType string) (bool, error) {
	row := q.db.QueryRow(ctx, getConnectorEnabled, connectorType)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listConnectorSettings = `-- name: ListConnectorSettings :many
SELECT connector_type, enabled, updated_at FROM connector_settings ORDER BY connector_type
`

func (q *Queries) ListConnectorSettings(ctx context.Context) ([]ConnectorSetting, error) {
	rows, err := q.db.Query(ctx, listConnectorSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectorSetting
	for rows.Next() {
		var i ConnectorSetting
		if err := rows.Scan(&i.ConnectorType, &i.Enabled, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnectorEnabled = `-- name: UpsertConnectorEnabled :one
INSERT INTO connector_settings (connector_type, enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (connector_type) DO UPDATE SET
  enabled = EXCLUDED.enabled,
  updated_at = now()
RETURNING connector_type, enabled, updated_at
`

type UpsertConnectorEnabledParams struct {
	ConnectorType string
	Enabled       bool
}

func (q *Queries) UpsertConnectorEnabled(ctx context.Context, arg UpsertConnectorEnabledParams) (ConnectorSetting, error) {
	row := q.db.QueryRow(ctx, upsertConnectorEnabled, arg.ConnectorType, arg.Enabled)
	var i ConnectorSetting
	err := row.Scan(&i.ConnectorType, &i.Enabled, &i.UpdatedAt)
	return i, err
}
