// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: connections.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateOAuthConnection = `-- name: ActivateOAuthConnection :exec
UPDATE connections
SET credential = $2,
    secret_key_version = $3,
    status = 'active',
    access_token_expires_at = $4,
    oauth_client_id = $5,
    updated_at = now()
WHERE id = $1
`

type ActivateOAuthConnectionParams struct {
	ID                   uuid.UUID
	Credential           []byte
	SecretKeyVersion     int32
	AccessTokenExpiresAt *time.Time
	OauthClientID        *uuid.UUID
}

func (q *Queries) ActivateOAuthConnection(ctx context.Context, arg ActivateOAuthConnectionParams) error {
	_, err := q.db.Exec(ctx, activateOAuthConnection,
		arg.ID,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.AccessTokenExpiresAt,
		arg.OauthClientID,
	)
	return err
}

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (
  id, connector_type, alias, auth_method, credential, secret_key_version,
  profile, scopes, status, access_token_expires_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, '{}', $7, $8, $9, now(), now()
)
RETURNING id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, oauth_client_id, created_at, updated_at
`

type CreateConnectionParams struct {
	ID                   uuid.UUID
	ConnectorType        string
	Alias                *string
	AuthMethod           string
	Credential           []byte
	SecretKeyVersion     int32
	Scopes               []string
	Status               string
	AccessTokenExpiresAt *time.Time
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.ID,
		arg.ConnectorType,
		arg.Alias,
		arg.AuthMethod,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.Scopes,
		arg.Status,
		arg.AccessTokenExpiresAt,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.OauthClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnection = `-- name: GetConnection :one
SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, oauth_client_id, created_at, updated_at FROM connections WHERE id = $1
`

func (q *Queries) GetConnection(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.OauthClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionForUpdate = `-- name: GetConnectionForUpdate :one
SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, oauth_client_id, created_at, updated_at FROM connections WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetConnectionForUpdate(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionForUpdate, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.OauthClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, oauth_client_id, created_at, updated_at FROM connections ORDER BY created_at DESC
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorType,
			&i.Alias,
			&i.AuthMethod,
			&i.Credential,
			&i.SecretKeyVersion,
			&i.Profile,
			&i.Scopes,
			&i.Status,
			&i.AccessTokenExpiresAt,
			&i.OauthClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingConnectionAuthorizationFailed = `-- name: MarkPendingConnectionAuthorizationFailed :exec
UPDATE connections
SET status = 'authorization_failed',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
`

func (q *Queries) MarkPendingConnectionAuthorizationFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPendingConnectionAuthorizationFailed, id)
	return err
}

const updateConnectionCredential = `-- name: UpdateConnectionCredential :exec
UPDATE connections
SET credential = $2,
    secret_key_version = $3,
    status = $4,
    access_token_expires_at = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateConnectionCredentialParams struct {
	ID                   uuid.UUID
	Credential           []byte
	SecretKeyVersion     int32
	Status               string
	AccessTokenExpiresAt *time.Time
}

func (q *Queries) UpdateConnectionCredential(ctx context.Context, arg UpdateConnectionCredentialParams) error {
	_, err := q.db.Exec(ctx, updateConnectionCredential,
		arg.ID,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.Status,
		arg.AccessTokenExpiresAt,
	)
	return err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE connections
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateConnectionStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateConnectionStatus, arg.ID, arg.Status)
	return err
}
