// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: connections.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConnectionAtPolicyIdentity = `-- name: CreateConnectionAtPolicyIdentity :one
WITH matched_policy AS (
  SELECT policy.connector_type
  FROM connector_policy_identities AS policy
  WHERE policy.connector_type = $2
    AND policy.initialized
    AND policy.identity_version = $12
    AND policy.identity_digest = $13
    AND policy.definition_digest = $14
  FOR SHARE
)
INSERT INTO connections (
  id, connector_type, alias, auth_method, credential, secret_key_version,
  profile, scopes, scopes_known, status, access_token_expires_at,
  created_at, updated_at
)
SELECT
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10,
  $11, now(), now()
FROM matched_policy
RETURNING id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, created_at, updated_at, authorization_generation, scopes_known, credential_version, authorization_attempt_version, refresh_owner, refresh_lease_until, refresh_state
`

type CreateConnectionAtPolicyIdentityParams struct {
	ID                       uuid.UUID
	ConnectorType            string
	Alias                    *string
	AuthMethod               string
	Credential               []byte
	SecretKeyVersion         int32
	Profile                  []byte
	Scopes                   []string
	ScopesKnown              bool
	Status                   string
	AccessTokenExpiresAt     *time.Time
	ExpectedIdentityVersion  int32
	ExpectedIdentityDigest   []byte
	ExpectedDefinitionDigest []byte
}

// Create only if the connector-wide policy still exactly matches the
// configuration used by the slow credential validator. FOR SHARE linearizes
// this INSERT against configsvc's FOR UPDATE writer: a writer that commits
// first makes the snapshot mismatch; a writer that commits second sees and
// bumps this newly inserted Connection.
func (q *Queries) CreateConnectionAtPolicyIdentity(ctx context.Context, arg CreateConnectionAtPolicyIdentityParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnectionAtPolicyIdentity,
		arg.ID,
		arg.ConnectorType,
		arg.Alias,
		arg.AuthMethod,
		arg.Credential,
		arg.SecretKeyVersion,
		arg.Profile,
		arg.Scopes,
		arg.ScopesKnown,
		arg.Status,
		arg.AccessTokenExpiresAt,
		arg.ExpectedIdentityVersion,
		arg.ExpectedIdentityDigest,
		arg.ExpectedDefinitionDigest,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationGeneration,
		&i.ScopesKnown,
		&i.CredentialVersion,
		&i.AuthorizationAttemptVersion,
		&i.RefreshOwner,
		&i.RefreshLeaseUntil,
		&i.RefreshState,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnection = `-- name: GetConnection :one
SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, created_at, updated_at, authorization_generation, scopes_known, credential_version, authorization_attempt_version, refresh_owner, refresh_lease_until, refresh_state FROM connections WHERE id = $1
`

func (q *Queries) GetConnection(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Alias,
		&i.AuthMethod,
		&i.Credential,
		&i.SecretKeyVersion,
		&i.Profile,
		&i.Scopes,
		&i.Status,
		&i.AccessTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationGeneration,
		&i.ScopesKnown,
		&i.CredentialVersion,
		&i.AuthorizationAttemptVersion,
		&i.RefreshOwner,
		&i.RefreshLeaseUntil,
		&i.RefreshState,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, connector_type, alias, auth_method, credential, secret_key_version, profile, scopes, status, access_token_expires_at, created_at, updated_at, authorization_generation, scopes_known, credential_version, authorization_attempt_version, refresh_owner, refresh_lease_until, refresh_state FROM connections ORDER BY created_at DESC
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorType,
			&i.Alias,
			&i.AuthMethod,
			&i.Credential,
			&i.SecretKeyVersion,
			&i.Profile,
			&i.Scopes,
			&i.Status,
			&i.AccessTokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorizationGeneration,
			&i.ScopesKnown,
			&i.CredentialVersion,
			&i.AuthorizationAttemptVersion,
			&i.RefreshOwner,
			&i.RefreshLeaseUntil,
			&i.RefreshState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
