// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exec.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertToolRun = `-- name: InsertToolRun :exec

insert into tool_runs (
  id, connector_type, connection_id, tool_id, session_id, api_token_id,
  status, error_kind, upstream_status, duration_ms, created_at
) values (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, now()
)
`

type InsertToolRunParams struct {
	ID             uuid.UUID
	ConnectorType  string
	ConnectionID   *uuid.UUID
	ToolID         string
	SessionID      *uuid.UUID
	ApiTokenID     *uuid.UUID
	Status         string
	ErrorKind      *string
	UpstreamStatus *int32
	DurationMs     *int32
}

// Tool 调用审计。
func (q *Queries) InsertToolRun(ctx context.Context, arg InsertToolRunParams) error {
	_, err := q.db.Exec(ctx, insertToolRun,
		arg.ID,
		arg.ConnectorType,
		arg.ConnectionID,
		arg.ToolID,
		arg.SessionID,
		arg.ApiTokenID,
		arg.Status,
		arg.ErrorKind,
		arg.UpstreamStatus,
		arg.DurationMs,
	)
	return err
}
