// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exec.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getConnectorConfigVerification = `-- name: GetConnectorConfigVerification :one
select mcp_verified_at, mcp_verified_endpoint
from connector_configs
where connector_type = $1
`

type GetConnectorConfigVerificationRow struct {
	McpVerifiedAt       *time.Time
	McpVerifiedEndpoint *string
}

func (q *Queries) GetConnectorConfigVerification(ctx context.Context, connectorType string) (GetConnectorConfigVerificationRow, error) {
	row := q.db.QueryRow(ctx, getConnectorConfigVerification, connectorType)
	var i GetConnectorConfigVerificationRow
	err := row.Scan(&i.McpVerifiedAt, &i.McpVerifiedEndpoint)
	return i, err
}

const insertToolRun = `-- name: InsertToolRun :exec
insert into tool_runs (
  id, connector_type, connection_id, tool_id, session_id,
  status, error, error_code, upstream_status, input, output_summary,
  duration_ms, created_at
) values (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, now()
)
`

type InsertToolRunParams struct {
	ID             uuid.UUID
	ConnectorType  string
	ConnectionID   *uuid.UUID
	ToolID         string
	SessionID      *uuid.UUID
	Status         string
	Error          *string
	ErrorCode      *string
	UpstreamStatus *int32
	Input          []byte
	OutputSummary  *string
	DurationMs     *int32
}

func (q *Queries) InsertToolRun(ctx context.Context, arg InsertToolRunParams) error {
	_, err := q.db.Exec(ctx, insertToolRun,
		arg.ID,
		arg.ConnectorType,
		arg.ConnectionID,
		arg.ToolID,
		arg.SessionID,
		arg.Status,
		arg.Error,
		arg.ErrorCode,
		arg.UpstreamStatus,
		arg.Input,
		arg.OutputSummary,
		arg.DurationMs,
	)
	return err
}

const setConnectorConfigVerified = `-- name: SetConnectorConfigVerified :exec
update connector_configs
set mcp_verified_at = now(),
    mcp_verified_endpoint = $1,
    updated_at = now()
where connector_type = $2
`

type SetConnectorConfigVerifiedParams struct {
	Endpoint      *string
	ConnectorType string
}

func (q *Queries) SetConnectorConfigVerified(ctx context.Context, arg SetConnectorConfigVerifiedParams) error {
	_, err := q.db.Exec(ctx, setConnectorConfigVerified, arg.Endpoint, arg.ConnectorType)
	return err
}

const upsertConnectorHealthFailure = `-- name: UpsertConnectorHealthFailure :exec
insert into connector_health (connector_type, last_error_at, consecutive_failures, last_error)
values ($1, now(), 1, $2)
on conflict (connector_type) do update
set last_error_at = now(),
    consecutive_failures = connector_health.consecutive_failures + 1,
    last_error = excluded.last_error
`

type UpsertConnectorHealthFailureParams struct {
	ConnectorType string
	LastError     *string
}

func (q *Queries) UpsertConnectorHealthFailure(ctx context.Context, arg UpsertConnectorHealthFailureParams) error {
	_, err := q.db.Exec(ctx, upsertConnectorHealthFailure, arg.ConnectorType, arg.LastError)
	return err
}

const upsertConnectorHealthSuccess = `-- name: UpsertConnectorHealthSuccess :exec

insert into connector_health (connector_type, last_ok_at, consecutive_failures)
values ($1, now(), 0)
on conflict (connector_type) do update
set last_ok_at = now(),
    consecutive_failures = 0
`

// 计划 4：Tool 执行引擎所需查询。
// connection 读取复用计划 3 的 GetConnection；GetConnectorHealth 在 connector_health.sql。
func (q *Queries) UpsertConnectorHealthSuccess(ctx context.Context, connectorType string) error {
	_, err := q.db.Exec(ctx, upsertConnectorHealthSuccess, connectorType)
	return err
}
