// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcp_sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMCPSession = `-- name: CreateMCPSession :exec
INSERT INTO mcp_sessions (
  id, token_hash, api_token_id, connection_id, tool_snapshot, expires_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, now())
`

type CreateMCPSessionParams struct {
	ID           uuid.UUID
	TokenHash    string
	ApiTokenID   uuid.UUID
	ConnectionID uuid.UUID
	ToolSnapshot []byte
	ExpiresAt    time.Time
}

func (q *Queries) CreateMCPSession(ctx context.Context, arg CreateMCPSessionParams) error {
	_, err := q.db.Exec(ctx, createMCPSession,
		arg.ID,
		arg.TokenHash,
		arg.ApiTokenID,
		arg.ConnectionID,
		arg.ToolSnapshot,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredMCPSessions = `-- name: DeleteExpiredMCPSessions :exec
DELETE FROM mcp_sessions
WHERE expires_at <= now()
   OR api_token_id IN (SELECT id FROM api_tokens WHERE revoked_at IS NOT NULL)
`

func (q *Queries) DeleteExpiredMCPSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMCPSessions)
	return err
}

const getMCPSessionByTokenHash = `-- name: GetMCPSessionByTokenHash :one
SELECT s.id, s.token_hash, s.api_token_id, s.connection_id, s.tool_snapshot, s.expires_at, s.created_at
FROM mcp_sessions s
JOIN api_tokens t ON t.id = s.api_token_id
WHERE s.token_hash = $1
  AND t.revoked_at IS NULL
`

func (q *Queries) GetMCPSessionByTokenHash(ctx context.Context, tokenHash string) (McpSession, error) {
	row := q.db.QueryRow(ctx, getMCPSessionByTokenHash, tokenHash)
	var i McpSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ApiTokenID,
		&i.ConnectionID,
		&i.ToolSnapshot,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
