// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type AdminAccount struct {
	ID           int32
	Username     string
	PasswordHash string
	UpdatedAt    time.Time
}

type ApiToken struct {
	ID        uuid.UUID
	Name      string
	TokenHash string
	CreatedAt time.Time
	RevokedAt *time.Time
}

type Connection struct {
	ID                   uuid.UUID
	ConnectorType        string
	Alias                *string
	AuthMethod           string
	Credential           []byte
	SecretKeyVersion     int32
	Profile              []byte
	Scopes               []string
	Status               string
	AccessTokenExpiresAt *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ConnectorConfig struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
	McpVerifiedEndpoint *string
	McpVerifiedAt       *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ConnectorHealth struct {
	ConnectorType       string
	LastOkAt            *time.Time
	LastErrorAt         *time.Time
	ConsecutiveFailures int32
	LastError           *string
}

type McpSession struct {
	ID            uuid.UUID
	TokenHash     string
	ToolAllowlist []byte
	Status        string
	ExpiresAt     time.Time
	CreatedAt     time.Time
}

type McpSessionConnection struct {
	SessionID    uuid.UUID
	Alias        string
	ConnectionID uuid.UUID
}

type OauthAuthorization struct {
	ID               uuid.UUID
	ConnectorType    string
	StateHash        string
	PkceVerifier     []byte
	ConnectionID     *uuid.UUID
	Status           string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	AuthMethod       string
	Alias            string
	SecretKeyVersion int32
	RedirectUrl      string
}

type ToolRun struct {
	ID            uuid.UUID
	ConnectorType string
	ConnectionID  *uuid.UUID
	ToolID        string
	SessionID     *uuid.UUID
	Status        string
	Error         *string
	Input         []byte
	OutputSummary *string
	DurationMs    *int32
	CreatedAt     time.Time
}
