// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type AdminAccount struct {
	ID           int32
	Username     string
	PasswordHash string
	UpdatedAt    time.Time
}

type ApiToken struct {
	ID        uuid.UUID
	Name      string
	TokenHash string
	CreatedAt time.Time
	RevokedAt *time.Time
}

type Connection struct {
	ID                   uuid.UUID
	ConnectorType        string
	Alias                *string
	AuthMethod           string
	Credential           []byte
	SecretKeyVersion     int32
	Profile              []byte
	Scopes               []string
	Status               string
	AccessTokenExpiresAt *time.Time
	OauthClientID        *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ConnectorConfig struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type McpSession struct {
	ID           uuid.UUID
	TokenHash    string
	ApiTokenID   uuid.UUID
	ToolSnapshot []byte
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type McpSessionConnection struct {
	SessionID    uuid.UUID
	Alias        string
	ConnectionID uuid.UUID
}

type OauthAuthorization struct {
	ID               uuid.UUID
	ConnectorType    string
	StateHash        string
	PkceVerifier     []byte
	SecretKeyVersion int32
	AuthMethod       string
	ConnectionID     uuid.UUID
	OauthClientID    *uuid.UUID
	Status           string
	ExpiresAt        time.Time
	CreatedAt        time.Time
}

type OauthClient struct {
	ID                      uuid.UUID
	ConnectorType           string
	Resource                string
	Issuer                  string
	RedirectUri             string
	ClientID                string
	ClientSecret            []byte
	SecretKeyVersion        int32
	TokenEndpoint           string
	TokenEndpointAuthMethod string
	ClientSecretExpiresAt   *time.Time
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type ToolRun struct {
	ID             uuid.UUID
	ConnectorType  string
	ConnectionID   *uuid.UUID
	ToolID         string
	SessionID      *uuid.UUID
	ApiTokenID     *uuid.UUID
	Status         string
	ErrorKind      *string
	UpstreamStatus *int32
	DurationMs     *int32
	CreatedAt      time.Time
}
