// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type AdminAccount struct {
	ID           int32
	Username     string
	PasswordHash string
	UpdatedAt    time.Time
}

type ApiToken struct {
	ID        uuid.UUID
	Name      string
	TokenHash string
	CreatedAt time.Time
	RevokedAt *time.Time
}

type Connection struct {
	ID                          uuid.UUID
	ConnectorType               string
	Alias                       *string
	AuthMethod                  string
	Credential                  []byte
	SecretKeyVersion            int32
	Profile                     []byte
	Scopes                      []string
	Status                      string
	AccessTokenExpiresAt        *time.Time
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	AuthorizationGeneration     int64
	ScopesKnown                 bool
	CredentialVersion           int64
	AuthorizationAttemptVersion int64
	RefreshOwner                *uuid.UUID
	RefreshLeaseUntil           *time.Time
	RefreshState                *string
}

type ConnectorConfig struct {
	ConnectorType       string
	ConfigSchemaVersion int32
	PublicConfig        []byte
	SecretConfig        []byte
	SecretKeyVersion    int32
	McpVerifiedEndpoint *string
	McpVerifiedAt       *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ConnectorHealth struct {
	ConnectorType       string
	LastOkAt            *time.Time
	LastErrorAt         *time.Time
	ConsecutiveFailures int32
	LastError           *string
}

type ConnectorPolicyIdentity struct {
	ConnectorType    string
	IdentityVersion  int32
	IdentityDigest   []byte
	DefinitionDigest []byte
	Initialized      bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type McpSession struct {
	ID            uuid.UUID
	TokenHash     string
	ToolAllowlist []byte
	Status        string
	ExpiresAt     time.Time
	CreatedAt     time.Time
}

type McpSessionConnection struct {
	SessionID               uuid.UUID
	Alias                   string
	ConnectionID            uuid.UUID
	AuthorizationGeneration int64
}

type OauthAuthorization struct {
	ID                              uuid.UUID
	ConnectorType                   string
	StateHash                       string
	ContextCiphertext               []byte
	ConnectionID                    uuid.UUID
	Status                          string
	ExpiresAt                       time.Time
	CreatedAt                       time.Time
	AuthMethod                      string
	Alias                           string
	SecretKeyVersion                int32
	RedirectUrl                     string
	AttemptVersion                  int64
	ExpectedAuthorizationGeneration int64
	FlowKind                        string
	RequestedScopes                 []string
	ContextVersion                  int16
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type ToolRun struct {
	ID             uuid.UUID
	ConnectorType  string
	ConnectionID   *uuid.UUID
	ToolID         string
	SessionID      *uuid.UUID
	Status         string
	Error          *string
	ErrorCode      *string
	UpstreamStatus *int32
	Input          []byte
	OutputSummary  *string
	DurationMs     *int32
	CreatedAt      time.Time
}
