// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_authorizations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOAuthAuthorization = `-- name: ClaimOAuthAuthorization :one
UPDATE oauth_authorizations
SET status = 'processing'
WHERE state_hash = $1
  AND status = 'pending'
  AND expires_at >= now()
RETURNING id, connector_type, state_hash, pkce_verifier, secret_key_version, auth_method, connection_id, redirect_url, status, expires_at, created_at
`

func (q *Queries) ClaimOAuthAuthorization(ctx context.Context, stateHash string) (OauthAuthorization, error) {
	row := q.db.QueryRow(ctx, claimOAuthAuthorization, stateHash)
	var i OauthAuthorization
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.StateHash,
		&i.PkceVerifier,
		&i.SecretKeyVersion,
		&i.AuthMethod,
		&i.ConnectionID,
		&i.RedirectUrl,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAuthorization = `-- name: CreateOAuthAuthorization :one
INSERT INTO oauth_authorizations (
  id, connector_type, state_hash, pkce_verifier, secret_key_version,
  auth_method, connection_id, redirect_url, status, expires_at, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, now()
)
RETURNING id, connector_type, state_hash, pkce_verifier, secret_key_version, auth_method, connection_id, redirect_url, status, expires_at, created_at
`

type CreateOAuthAuthorizationParams struct {
	ID               uuid.UUID
	ConnectorType    string
	StateHash        string
	PkceVerifier     []byte
	SecretKeyVersion int32
	AuthMethod       string
	ConnectionID     uuid.UUID
	RedirectUrl      string
	ExpiresAt        time.Time
}

func (q *Queries) CreateOAuthAuthorization(ctx context.Context, arg CreateOAuthAuthorizationParams) (OauthAuthorization, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorization,
		arg.ID,
		arg.ConnectorType,
		arg.StateHash,
		arg.PkceVerifier,
		arg.SecretKeyVersion,
		arg.AuthMethod,
		arg.ConnectionID,
		arg.RedirectUrl,
		arg.ExpiresAt,
	)
	var i OauthAuthorization
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.StateHash,
		&i.PkceVerifier,
		&i.SecretKeyVersion,
		&i.AuthMethod,
		&i.ConnectionID,
		&i.RedirectUrl,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClaimedOAuthAuthorization = `-- name: DeleteClaimedOAuthAuthorization :execrows
DELETE FROM oauth_authorizations
WHERE id = $1
  AND status = 'processing'
`

func (q *Queries) DeleteClaimedOAuthAuthorization(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClaimedOAuthAuthorization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireOAuthAuthorizations = `-- name: ExpireOAuthAuthorizations :exec
WITH expired AS (
  DELETE FROM oauth_authorizations
  WHERE (status = 'pending' AND expires_at < now())
     OR (status = 'processing' AND expires_at < now() - interval '1 minute')
  RETURNING connection_id
)
UPDATE connections
SET status = 'authorization_failed',
    updated_at = now()
WHERE id IN (
  SELECT connection_id
  FROM expired
)
  AND status = 'pending'
`

func (q *Queries) ExpireOAuthAuthorizations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOAuthAuthorizations)
	return err
}

const supersedeOpenOAuthAuthorizations = `-- name: SupersedeOpenOAuthAuthorizations :exec
DELETE FROM oauth_authorizations
WHERE connection_id = $1
  AND status IN ('pending', 'processing')
`

func (q *Queries) SupersedeOpenOAuthAuthorizations(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, supersedeOpenOAuthAuthorizations, connectionID)
	return err
}
