// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_clients.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (
  id, connector_type, resource, issuer, redirect_uri,
  client_id, client_secret, secret_key_version,
  token_endpoint, token_endpoint_auth_method, client_secret_expires_at,
  created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  $9, $10, $11,
  now(), now()
)
RETURNING id, connector_type, resource, issuer, redirect_uri, client_id, client_secret, secret_key_version, token_endpoint, token_endpoint_auth_method, client_secret_expires_at, created_at, updated_at
`

type CreateOAuthClientParams struct {
	ID                      uuid.UUID
	ConnectorType           string
	Resource                string
	Issuer                  string
	RedirectUri             string
	ClientID                string
	ClientSecret            []byte
	SecretKeyVersion        int32
	TokenEndpoint           string
	TokenEndpointAuthMethod string
	ClientSecretExpiresAt   *time.Time
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.ConnectorType,
		arg.Resource,
		arg.Issuer,
		arg.RedirectUri,
		arg.ClientID,
		arg.ClientSecret,
		arg.SecretKeyVersion,
		arg.TokenEndpoint,
		arg.TokenEndpointAuthMethod,
		arg.ClientSecretExpiresAt,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Resource,
		&i.Issuer,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.SecretKeyVersion,
		&i.TokenEndpoint,
		&i.TokenEndpointAuthMethod,
		&i.ClientSecretExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireOAuthClientRegistration = `-- name: ExpireOAuthClientRegistration :exec
UPDATE oauth_clients
SET client_secret_expires_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ExpireOAuthClientRegistration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireOAuthClientRegistration, id)
	return err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, connector_type, resource, issuer, redirect_uri, client_id, client_secret, secret_key_version, token_endpoint, token_endpoint_auth_method, client_secret_expires_at, created_at, updated_at FROM oauth_clients WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id uuid.UUID) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Resource,
		&i.Issuer,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.SecretKeyVersion,
		&i.TokenEndpoint,
		&i.TokenEndpointAuthMethod,
		&i.ClientSecretExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthClientByRegistration = `-- name: GetOAuthClientByRegistration :one
SELECT id, connector_type, resource, issuer, redirect_uri, client_id, client_secret, secret_key_version, token_endpoint, token_endpoint_auth_method, client_secret_expires_at, created_at, updated_at
FROM oauth_clients
WHERE connector_type = $1
  AND resource = $2
  AND issuer = $3
  AND redirect_uri = $4
`

type GetOAuthClientByRegistrationParams struct {
	ConnectorType string
	Resource      string
	Issuer        string
	RedirectUri   string
}

func (q *Queries) GetOAuthClientByRegistration(ctx context.Context, arg GetOAuthClientByRegistrationParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByRegistration,
		arg.ConnectorType,
		arg.Resource,
		arg.Issuer,
		arg.RedirectUri,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Resource,
		&i.Issuer,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.SecretKeyVersion,
		&i.TokenEndpoint,
		&i.TokenEndpointAuthMethod,
		&i.ClientSecretExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOAuthClientRegistration = `-- name: LockOAuthClientRegistration :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockOAuthClientRegistration(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockOAuthClientRegistration, hashtextextended)
	return err
}

const replaceOAuthClientRegistration = `-- name: ReplaceOAuthClientRegistration :one
UPDATE oauth_clients
SET client_id = $2,
    client_secret = $3,
    secret_key_version = $4,
    token_endpoint = $5,
    token_endpoint_auth_method = $6,
    client_secret_expires_at = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, connector_type, resource, issuer, redirect_uri, client_id, client_secret, secret_key_version, token_endpoint, token_endpoint_auth_method, client_secret_expires_at, created_at, updated_at
`

type ReplaceOAuthClientRegistrationParams struct {
	ID                      uuid.UUID
	ClientID                string
	ClientSecret            []byte
	SecretKeyVersion        int32
	TokenEndpoint           string
	TokenEndpointAuthMethod string
	ClientSecretExpiresAt   *time.Time
}

func (q *Queries) ReplaceOAuthClientRegistration(ctx context.Context, arg ReplaceOAuthClientRegistrationParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, replaceOAuthClientRegistration,
		arg.ID,
		arg.ClientID,
		arg.ClientSecret,
		arg.SecretKeyVersion,
		arg.TokenEndpoint,
		arg.TokenEndpointAuthMethod,
		arg.ClientSecretExpiresAt,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Resource,
		&i.Issuer,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.SecretKeyVersion,
		&i.TokenEndpoint,
		&i.TokenEndpointAuthMethod,
		&i.ClientSecretExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthClientEndpoint = `-- name: UpdateOAuthClientEndpoint :one
UPDATE oauth_clients
SET token_endpoint = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, connector_type, resource, issuer, redirect_uri, client_id, client_secret, secret_key_version, token_endpoint, token_endpoint_auth_method, client_secret_expires_at, created_at, updated_at
`

type UpdateOAuthClientEndpointParams struct {
	ID            uuid.UUID
	TokenEndpoint string
}

func (q *Queries) UpdateOAuthClientEndpoint(ctx context.Context, arg UpdateOAuthClientEndpointParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, updateOAuthClientEndpoint, arg.ID, arg.TokenEndpoint)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.Resource,
		&i.Issuer,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.SecretKeyVersion,
		&i.TokenEndpoint,
		&i.TokenEndpointAuthMethod,
		&i.ClientSecretExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
