// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_authorizations.sql

package store

import (
	"context"
)

const getOAuthAuthorizationByStateHash = `-- name: GetOAuthAuthorizationByStateHash :one
SELECT id, connector_type, state_hash, context_ciphertext, connection_id, status, expires_at, created_at, auth_method, alias, secret_key_version, redirect_url, attempt_version, expected_authorization_generation, flow_kind, requested_scopes, context_version FROM oauth_authorizations WHERE state_hash = $1
`

func (q *Queries) GetOAuthAuthorizationByStateHash(ctx context.Context, stateHash string) (OauthAuthorization, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationByStateHash, stateHash)
	var i OauthAuthorization
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.StateHash,
		&i.ContextCiphertext,
		&i.ConnectionID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AuthMethod,
		&i.Alias,
		&i.SecretKeyVersion,
		&i.RedirectUrl,
		&i.AttemptVersion,
		&i.ExpectedAuthorizationGeneration,
		&i.FlowKind,
		&i.RequestedScopes,
		&i.ContextVersion,
	)
	return i, err
}
