// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/account/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "修改管理员密码",
                "operationId": "changePassword",
                "parameters": [
                    {
                        "description": "新密码（至少 8 个字符）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/api-tokens": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "列出 API token（不含明文）",
                "operationId": "listApiTokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/authsvc.APITokenView"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "创建 API token（明文仅在响应中出现一次）",
                "operationId": "createApiToken",
                "parameters": [
                    {
                        "description": "token 名称",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.createTokenResponse"
                        }
                    }
                }
            }
        },
        "/admin/api-tokens/{id}": {
            "delete": {
                "tags": [
                    "admin"
                ],
                "summary": "撤销 API token",
                "operationId": "deleteApiToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token id（uuid）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/connections": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "列出全部连接（运维视角，不含 credential）",
                "operationId": "listConnections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/connsvc.ConnectionView"
                            }
                        }
                    }
                }
            }
        },
        "/admin/connections/{id}": {
            "delete": {
                "tags": [
                    "admin"
                ],
                "summary": "删除连接（运维）",
                "operationId": "adminDeleteConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connection id（uuid）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/connections/{id}/reauth": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "生成重授权链接（运维转交给对应用户打开）",
                "operationId": "adminReauthConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connection id（uuid）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.beginOAuthResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/connectors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "列出全部 Connector（管理界面，cookie 鉴权）",
                "operationId": "adminListConnectors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/catalogsvc.Item"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/connectors/{type}/auth-methods": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Connector 的认证方式与凭证字段（供创建 connection 的表单）",
                "operationId": "listAuthMethods",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector_type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.authMethodDTO"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/connectors/{type}/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "读取 Connector 配置（Secret 只回显已设置的 key）",
                "operationId": "getConfig",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector_type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.configResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "写入 Connector 配置（public 全量替换、secrets 增量合并，空串删除）",
                "operationId": "putConfig",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector_type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "配置内容；if_match 传上次读到的 updated_at（RFC3339），首次创建留空",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.putConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.configResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "admin"
                ],
                "summary": "删除 Connector 配置",
                "operationId": "deleteConfig",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector_type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/connectors/{type}/config-schema": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Connector 配置表单元数据（由 Definition 的 ConfigFields 生成）",
                "operationId": "getConfigSchema",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector_type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.configFieldDTO"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "管理员登录，成功后下发会话 cookie",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "用户名与密码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "健康检查",
                "operationId": "healthz",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/connections/api-key": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "用 API key / 自定义凭证创建连接，返回其持久 ID",
                "operationId": "createApiKeyConnection",
                "parameters": [
                    {
                        "description": "凭证字段按 auth method 的 CredentialFields 填写；alias 可选",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.createConnectionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/connections/oauth": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "发起 OAuth 授权：立即创建 pending 连接并返回其持久 ID 与授权 URL",
                "operationId": "beginOAuthConnection",
                "parameters": [
                    {
                        "description": "alias 为可选展示标签",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.beginOAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.beginOAuthResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/connections/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "查询连接状态（pending / active / reauth_required …）",
                "operationId": "getConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connection id（uuid）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connsvc.ConnectionView"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "connections"
                ],
                "summary": "删除连接",
                "operationId": "deleteConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connection id（uuid）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/connections/{id}/reauth": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "对既有连接重新发起授权（ID 不变）",
                "operationId": "reauthConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connection id（uuid）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.beginOAuthResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/connectors": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "列出全部 Connector（含运行状态）",
                "operationId": "listConnectors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/catalogsvc.Item"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/connectors/{type}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "查询单个 Connector",
                "operationId": "getConnector",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector_type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalogsvc.Item"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mcp-sessions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mcp"
                ],
                "summary": "签发聚合多个 Connection 的短期 MCP session token",
                "operationId": "createMcpSession",
                "parameters": [
                    {
                        "description": "connections 为 namespace→connection_id；allowlist 使用 namespace__tool 名称",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createMCPSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.createMCPSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/oauth/callback": {
            "get": {
                "tags": [
                    "connections"
                ],
                "summary": "OAuth 回调（provider 跳转回来，无鉴权，靠一次性 state）",
                "operationId": "oauthCallback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "授权发起时生成的 state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "授权码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "provider 返回的错误码",
                        "name": "error",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.authMethodDTO": {
            "type": "object",
            "properties": {
                "credential_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.configFieldDTO"
                    }
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.beginOAuthRequest": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "auth_method": {
                    "type": "string"
                },
                "connector_type": {
                    "type": "string"
                }
            }
        },
        "api.beginOAuthResponse": {
            "type": "object",
            "properties": {
                "authorization_url": {
                    "type": "string"
                },
                "connection_id": {
                    "type": "string"
                }
            }
        },
        "api.changePasswordRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "api.configFieldDTO": {
            "type": "object",
            "properties": {
                "default_value": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "input_type": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pattern": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "secret": {
                    "type": "boolean"
                }
            }
        },
        "api.configResponse": {
            "type": "object",
            "properties": {
                "connector_type": {
                    "type": "string"
                },
                "public": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "schema_version": {
                    "type": "integer"
                },
                "secret_keys_set": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.createAPIKeyRequest": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "auth_method": {
                    "type": "string"
                },
                "connector_type": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "api.createConnectionResponse": {
            "type": "object",
            "properties": {
                "connection_id": {
                    "type": "string"
                }
            }
        },
        "api.createMCPSessionRequest": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "tool_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ttl_seconds": {
                    "type": "integer"
                }
            }
        },
        "api.createMCPSessionResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.createTokenRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api.createTokenResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.putConfigRequest": {
            "type": "object",
            "properties": {
                "if_match": {
                    "type": "string"
                },
                "public": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "secrets": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "authsvc.APITokenView": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                }
            }
        },
        "catalogsvc.AuthMethodSummary": {
            "type": "object",
            "properties": {
                "credential_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogsvc.CredentialField"
                    }
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/connector.AuthMethodType"
                }
            }
        },
        "catalogsvc.CredentialField": {
            "type": "object",
            "properties": {
                "default_value": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "input_type": {
                    "$ref": "#/definitions/connector.ConfigInputType"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pattern": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "secret": {
                    "type": "boolean"
                }
            }
        },
        "catalogsvc.Item": {
            "type": "object",
            "properties": {
                "auth_methods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogsvc.AuthMethodSummary"
                    }
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "homepage_url": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "mode": {
                    "$ref": "#/definitions/connector.Mode"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/status.Status"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "connector.AuthMethodType": {
            "type": "string",
            "enum": [
                "none",
                "oauth2",
                "api_key",
                "custom_credential"
            ],
            "x-enum-varnames": [
                "AuthNone",
                "AuthOAuth2",
                "AuthAPIKey",
                "AuthCustomCredential"
            ]
        },
        "connector.ConfigInputType": {
            "type": "string",
            "enum": [
                "text",
                "select"
            ],
            "x-enum-varnames": [
                "InputText",
                "InputSelect"
            ]
        },
        "connector.Mode": {
            "type": "string",
            "enum": [
                "remote_mcp",
                "managed"
            ],
            "x-enum-varnames": [
                "ModeRemoteMCP",
                "ModeManaged"
            ]
        },
        "connsvc.ConnectionView": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "auth_method": {
                    "type": "string"
                },
                "connector_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "status.Status": {
            "type": "string",
            "enum": [
                "needs_config",
                "config_incompatible",
                "ready",
                "deprecated",
                "definition_missing"
            ],
            "x-enum-varnames": [
                "NeedsConfig",
                "ConfigIncompatible",
                "Ready",
                "Deprecated",
                "DefinitionMissing"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "connect-it API",
	Description:      "内部 Connector 服务：catalog、配置管理、OAuth 连接与聚合 MCP。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
